import {rows,saveRow} from './local-tools.js?v=0.4.14';
import {validateGuidance,ownNote} from './connection-inputs.js?v=0.4.14';
import {ATTRACTION_FIELDS,FRAMEWORK_FIELDS} from './attraction-data.js?v=0.4.14';
import {validateDisclosure} from './connection-sharing.js?v=0.4.14';

export const RHYTHM_FIELDS=[
 {key:'Planning style',label:'How planned or spontaneous?',type:'scale',options:['Fully planned','Mostly planned','A mix','Mostly spontaneous','In the moment'],hint:'Choose how much advance planning feels right. You can add exceptions in your own words.'},
 {key:'Novelty and randomness',label:'Predictability or random discovery?',type:'scale',options:['Familiar and predictable','Mostly familiar','A mix','Usually something new','Random discovery'],hint:'How much variety and surprise do you enjoy? This is independent of how far ahead you plan.'}
];
export const SIMILARITY_FIELD={key:'Similarity and contrast',label:'Like minds or complementary opposites?',type:'scale',options:['Very like-minded','Mostly similar','Shared core, different interests','Enjoy contrasting qualities','Complementary opposites'],hint:'Think about interests, temperament and perspectives. Add which values you want to share and which differences you enjoy.'};
export const CULTURE_FIELDS=[
 {key:'Cultural connection',label:'Shared culture or intercultural connection?',type:'single',options:['Shared culture only','Prefer shared culture','Open to either','Prefer intercultural connection','Decide person by person'],hint:'Choose your preference, then add any traditions, languages or customs that matter to you.'},
 {key:'Faith connection',label:'Shared faith or interfaith connection?',type:'single',options:['Shared faith or worldview only','Prefer a shared faith or worldview','Open to interfaith connection','Faith is not a deciding factor','Decide person by person'],hint:'Faith or worldview can include a religion, spiritual outlook or no religion. Add what you would like to share or keep independent.'}
];

const choice=(key,label,options,hint='')=>({key,label,type:'choices',options:options.split('|'),hint});
const words=(key,label,hint='')=>({key,label,type:'text',hint});
const number=(key,label,min,max,unit,hint='')=>({key,label,type:'number',min,max,unit,hint});
const adultAgeHint='Actual years since birth, not apparent or biological age. Aura Dating is 18+; local consent and other legal requirements still apply.';
export const numericRange=f=>f.max==null?`${f.min}+ ${f.unit}`:`${f.min} to ${f.max} ${f.unit}`;
export const LOVE_LANGUAGES=[['words','Words of affirmation','Kind words, encouragement and appreciation'],['time','Quality time','Attention and time together'],['help','Acts of service','Practical help and thoughtful effort'],['gifts','Receiving gifts','Thoughtful things and remembered occasions'],['touch','Physical touch','Affection and welcome closeness']];
export const DAYS=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
export const DAY_PARTS=['Morning','Afternoon','Evening'];
export const DATING_CHAPTERS=[
 {id:'identity',title:'Me & attraction',short:'Identity',colour:'#9165c2',icon:'identity',intro:'Your experience, attraction and chosen life chapter can evolve across an extended life.',fields:[
  words('Display name','What name would you like to use?'),words('Gender','How do you describe your gender?','Use your own words, or leave this open.'),number('Chronological age','Your chronological age',18,null,'years',adultAgeHint),
  choice('Sexuality','How do you describe your sexuality?','Straight|Gay|Lesbian|Bisexual|Pansexual|Queer|Asexual|Demisexual|Questioning|Prefer my own words','Choose more than one if useful. Labels are optional.'),words('Identity notes','Anything else about your identity or attraction?'),words('Attracted to','Who are you interested in meeting?','Gender, presentation, qualities or your own description.'),number('Age minimum','Youngest adult you would like to date',18,null,'years',adultAgeHint),number('Age maximum','Oldest adult you would like to date',18,null,'years','Leave blank for no upper age preference. '+adultAgeHint)]},
 {id:'intentions',title:'Life chapters & intentions',short:'Life chapters',colour:'#c05a86',icon:'heart',intro:'Plan for radical longevity and possible age reversal: a future scenario with many life chapters, rather than a fixed life timetable.',fields:[
  choice('Connection wanted','What are you open to?','Romance|Long-term partnership|Casual dating|Companionship|Friendship first|Intimacy|Marriage|Exploring|Shared projects|Renewable commitments'),choice('Relationship shape','What relationship arrangements suit you?','Monogamy|Consensual non-monogamy|Polyamory|Open relationship|Relationship anarchy|Still exploring','These are conversation starters, not assumptions about anyone else.'),words('Hopes','What would connection add to this chapter of your life?','Companionship, discovery, intimacy, shared work or a future you choose together.'),words('Pace','What pace feels right?','Friendly first, direct intentions, slow trust or something else.'),words('Current situation','Which life chapter are you choosing now?','Learning again, creating, exploring, rebuilding, caring or beginning something new.'),words('Longevity outlook','How do age reversal and radical longevity shape your relationship outlook?','Assume they are possible for this planning exercise. What would you want to explore or change?'),choice('Planning horizon','What horizons would you like to explore together?','The present|A shared season|Several years|Decades|Centuries or longer|Open-ended','Select horizons that interest you, not a promise of lifespan.'),words('Renewing agreements','How would you revisit commitments as each of you changes?','Check-ins, new chapters, continuity, renewed agreements or parting well.')]},
 {id:'love',title:'Five love languages',short:'Love languages',colour:'#bd5074',icon:'love',intro:'Explore how you like to give and receive affection. These are preferences, not a personality test.',fields:[{key:'Love giving',label:'How you give affection',type:'love'},{key:'Love receiving',label:'How you receive affection',type:'love'},words('Love examples','What does feeling loved look like in everyday life?','Small gestures, welcome touch, attention or something you would like to ask for.')]},
 {id:'appearance',title:'Appearance & attraction',short:'Appearance',colour:'#b87a3d',icon:'appearance',intro:'Explore present attraction and how appearance, vitality and preferences could evolve with rejuvenation.',fields:[
  words('My appearance','How would you describe your appearance?','Build, hair, height, features or whatever feels relevant.'),number('My height','Your height',80,260,'cm'),choice('My style','How do you like to present yourself?','Casual|Elegant|Sporty|Alternative|Creative|Outdoorsy|Minimal|Glamorous|Androgynous|Changes with the day'),choice('Attraction cues','What draws your attention?','Face & smile|Eyes|Body & build|Hair|Height|Voice|Movement|Style|Scent|Presence|Personality first|No fixed type'),words('Appearance preferences','What appearance or presentation do you find attractive?','Describe preferences in your own words.'),words('Attraction flexibility','What is a preference, and what matters more once you know someone?'),words('Rejuvenation preferences','If rejuvenation became possible, what would you choose for yourself?','Appearance, vitality, physical capabilities or continuity with your present self.')]},
 {id:'personality',title:'Personality & values',short:'Personality',colour:'#987b28',icon:'spark',intro:'Describe both your own nature and the qualities you enjoy in others.',fields:[
  choice('My personality','Which qualities feel like you?','Quiet|Outgoing|Playful|Reflective|Curious|Practical|Spontaneous|Organised|Sensitive|Direct|Adventurous|Creative'),choice('Drawn to qualities','Which qualities do you enjoy in a partner?','Warmth|Humour|Curiosity|Reliability|Ambition|Gentleness|Confidence|Creativity|Independence|Spiritual depth|Patience|Adventure'),words('Values','What values matter most?','Culture, spirituality, kindness, responsibility, politics, family or your own priorities.'),words('Personality frameworks','Any personality frameworks you use?','Your own descriptions or self-reported frameworks. No type is assigned by Aura.'),words('Differences welcome','What differences could enrich your connection?','Language, culture, interests, neurotype, background or ways of seeing the world.')]},
 {id:'emotional',title:'Emotional availability',short:'Emotional space',colour:'#49958a',icon:'emotional',intro:'How much space is there for connection, and what helps trust grow?',fields:[
  choice('Emotional availability','What describes your emotional availability right now?','Ready to connect|Taking it slowly|Rebuilding trust|Need more space|Open but stretched|Unsure'),words('Emotional needs','What helps you feel understood and secure?'),choice('Communication style','How do you like to communicate?','Direct words|Gentle questions|Time to think|Talk in person|Written messages|Regular check-ins|Humour|Quiet together'),words('Conflict and repair','What helps during disagreement and afterwards?','How you pause, return to a conversation, apologise and reconnect.'),words('Care and support','How would you support each other through renewal and changing needs?','Reinvention, periods of care, new pursuits or different emotional rhythms.'),words('Emotional boundaries','What is not ready to be explored yet?')]},
 {id:'intimacy',title:'Intimacy & kinks',short:'Intimacy',colour:'#835e9f',icon:'intimacy',intro:'Your own adult interests, curiosities and limits. Preferences begin a conversation; they are not consent.',fields:[
  choice('Intimacy interests','What would you like to explore or enjoy?','Affection|Cuddling|Sensuality|Sexual connection|Flirting|Massage|Kissing|Non-sexual closeness'),choice('Kink interests','Any kink interests or curiosities?','BDSM|Bondage|Power exchange|Role play|Sensory play|Fetish interests|Kink-free intimacy|Exploring|Prefer my own words','Use the next card to distinguish interests from curiosities.'),words('Kink notes','What interests you, and what are you only curious about?'),words('Intimacy rhythm','What pace or frequency feels comfortable?','Include changing needs or differences in desire.'),words('Intimacy yes maybe no','What is a yes, a maybe, or a no for you?'),words('Consent and aftercare','How do you like to check consent, pause and care for each other?'),words('Intimacy conversations','What conversations would you want before intimacy?','Comfort, safer sex, testing, contraception, privacy or anything important to you.')]},
 {id:'boundaries',title:'Trust & sharing',short:'Trust & boundaries',colour:'#587da9',icon:'shield',intro:'Choose what needs trust and what stays yours. These notes do not change app permissions.',fields:[
  words('Boundaries','What are your firm boundaries?'),words('Easy to share','What feels easy to share with someone new?'),words('Trust first','What needs trust before you share it?'),words('Keep private','What would you keep private?'),words('Ask first','What should someone ask before doing?','Introductions, sharing photos, changing plans, touch or discussing something personal.'),words('AI boundaries','If you later ask an AI for help, what should it use or leave out?')]},
 {id:'time',title:'Time & rhythm',short:'Time',colour:'#3f929c',icon:'clock',intro:'A realistic picture of the time and attention you have.',fields:[
  {key:'Weekly availability',label:'When are you usually free?',type:'week',hint:'Tap the times that usually suit you. This is a preference, not a calendar booking.'},number('Hours together','Time you would like together each week',0,168,'hours'),words('Availability','What affects your availability?','Work, care, study, changing shifts or energy.'),choice('Contact rhythm','How often would you like contact?','Most days|A few times a week|Weekly|Flexible|Agree together'),words('Time together','How do shared time, independent pursuits and longer life chapters fit together?')]},
 {id:'location',title:'Location & distance',short:'Location',colour:'#59835c',icon:'location',intro:'Where connection could fit into your everyday life.',fields:[
  words('Based near','Which town, city or region are you based near?'),number('Travel distance','How far would you usually travel to meet?',0,20000,'km'),choice('Meeting options','What kinds of connection work for you?','Nearby|Online first|Long distance|Travelling together|Meeting halfway|Open to relocating'),words('Location plans','Any upcoming travel or possible moves?'),words('Meeting preferences','What makes a good place to meet?','Quiet or lively, outdoors, public places, accessibility or transport.'),words('Time zone','Your time zone, if distance matters')]},
 {id:'life',title:'Shared futures',short:'Shared futures',colour:'#b5804c',icon:'home',intro:'Design a shared life that can grow, branch and renew, without assuming a standard sequence or endpoint.',fields:[
  choice('Shared activities','What would you enjoy together?','Walks|Food & cooking|Arts|Music|Learning|Travel|Sport|Nature|Games|Community|Quiet nights|Making things'),words('Activities','Any other ideas for time together?'),words('Family and children','What forms of family, kinship or care would you choose?','Parenthood, no parenthood, chosen family, shared care or evolving commitments. No sequence is assumed.'),words('Home and pets','How would you like to live, together or independently?','Separate homes, shared homes, communities, travel, pets or different arrangements over time.'),words('Lifestyle','What daily habits or lifestyle preferences matter?','Sleep, food, substances, faith, access needs, work or routines.'),words('Money and responsibilities','How would you like to approach money and shared responsibilities?'),words('Shared future','What would you build or experience across many life chapters?','Learning, travel, creative work, communities or projects that could span decades or longer.'),words('Continuity and change','What should endure, and what should remain free to change?')]},
 {id:'signals',title:'Green, amber & red',short:'Signals',colour:'#b66f52',icon:'signals',intro:'Borrowing from Grey Area Commons: recognise warmth, uncertainty and clear stopping points.',fields:[
  words('Green signals','What helps you relax and open up?','Reliability, mutual curiosity, humour, clear intentions or shared values.'),words('Amber signals','What means slow down and ask more?','Mixed signals, differences, uncertainty, distance or a busy season of life.'),words('Red signals','What means stop for you?'),words('First step','What makes a first approach feel welcome?'),words('Deeper questions','What would you like to learn about each other?')]}
];
DATING_CHAPTERS.find(c=>c.id==='time').fields.push(...RHYTHM_FIELDS);
DATING_CHAPTERS.find(c=>c.id==='personality').fields.push({...SIMILARITY_FIELD});
DATING_CHAPTERS.find(c=>c.id==='personality').fields.push(...CULTURE_FIELDS.map(f=>({...f})));
const attraction=DATING_CHAPTERS.find(c=>c.id==='appearance');
attraction.title='Attraction, body & senses';attraction.short='Attraction';
attraction.intro='What draws you in is yours to describe: bodies, senses, qualities, resources, familiar patterns or something entirely individual.';
const oldAttractionGroups={'My appearance':'About me','My height':'About me','My style':'About me','Attraction cues':'What draws me','Appearance preferences':'Body & looks','Attraction flexibility':'What draws me','Rejuvenation preferences':'About me'};
attraction.fields.forEach(f=>f.group=oldAttractionGroups[f.key]);
attraction.fields.unshift(...ATTRACTION_FIELDS);
const attractionGroups=['What draws me','Body & looks','Senses','Reflection','About me'];
attraction.fields.sort((a,b)=>attractionGroups.indexOf(a.group)-attractionGroups.indexOf(b.group));
const personality=DATING_CHAPTERS.find(c=>c.id==='personality');
personality.fields.forEach(f=>f.group=f.key==='Personality frameworks'?'Frameworks':'Qualities & values');
personality.fields.push(...FRAMEWORK_FIELDS);
personality.fields.sort((a,b)=>(a.group==='Frameworks')-(b.group==='Frameworks'));
export const profileFields=DATING_CHAPTERS.flatMap(c=>c.fields);
export function datingProfile(project){return rows(project,'aura-preferences').find(r=>r.id==='social-dating')||{};}
export function listValue(value){if(!value)return [];try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed:[];}catch{return [];}}
export function loveValue(value){if(!value)return {};try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed:{};}catch{return {};}}
export function fieldAnswered(field,value){if(!value)return false;if(['choices','week'].includes(field.type))return listValue(value).length>0;if(['love','weights'].includes(field.type))return Object.keys(loveValue(value)).length>0;return String(value).trim().length>0;}
export function chapterProgress(chapter,profile){return chapter.fields.filter(f=>fieldAnswered(f,profile[f.key])||ownNote(profile,f.key).trim()).length;}
export function savePreferenceProfile(project,fields,chapters,id,title){
 const values={...fields};delete values.id;
 const combined={...rows(project,'aura-preferences').find(r=>r.id===id),...values};
 validateGuidance(combined,chapters);
 validateDisclosure(combined,chapters);
 for(const f of chapters.flatMap(c=>c.fields)){const v=combined[f.key];if(v===undefined||v==='')continue;
  if(['scale','single'].includes(f.type)&&!f.options.includes(v))throw Error('Choose a valid option for '+f.label);
  if(f.type==='weights'){let values;try{values=JSON.parse(v);}catch{throw Error('Use valid attraction preferences.');}if(!values||Array.isArray(values)||typeof values!=='object'||Object.entries(values).some(([axis,n])=>!f.axes.includes(axis)||!Number.isInteger(n)||n<0||n>5))throw Error('Attraction preferences use independent values from 0 to 5.');}
  if(f.type==='number'&&(!Number.isFinite(Number(v))||Number(v)<f.min||(f.max!=null&&Number(v)>f.max)||(f.unit==='years'&&!Number.isSafeInteger(Number(v)))))throw Error(`${f.label}: use ${numericRange(f)}, or leave blank.`);
  if(['choices','week'].includes(f.type)){let a;try{a=JSON.parse(v);}catch{throw Error('Choose valid options for '+f.label);}const allowed=f.type==='week'?DAYS.flatMap(d=>DAY_PARTS.map(t=>d+' '+t)):f.options;if(!Array.isArray(a)||a.some(x=>!allowed.includes(x))||new Set(a).size!==a.length)throw Error('Choose valid options for '+f.label);}
  if(f.type==='love'){let obj;try{obj=JSON.parse(v);}catch{throw Error('Use valid love language preferences.');}if(!obj||Array.isArray(obj)||typeof obj!=='object'||Object.entries(obj).some(([k,n])=>!LOVE_LANGUAGES.some(l=>l[0]===k)||!Number.isInteger(n)||n<0||n>5))throw Error('Love language preferences use 0 to 5.');}
 }

 if(combined['Age minimum']&&combined['Age maximum']&&Number(combined['Age minimum'])>Number(combined['Age maximum']))throw Error('The youngest age should not exceed the oldest age.');
 return saveRow(project,'aura-preferences','System preferences',{...values,Title:title},id);
}

export const saveDatingProfile=(project,fields)=>savePreferenceProfile(project,fields,DATING_CHAPTERS,'social-dating','dating');
