import {framePoint} from './frame-display.js?v=0.4.12';
import {make,button,header} from './local-tools.js?v=0.4.12';
import {readTravelProject,writeTravelProject} from './travel-data.js?v=0.4.12';
import {DATING_CHAPTERS,LOVE_LANGUAGES,DAYS,DAY_PARTS,datingProfile,listValue,loveValue,chapterProgress,fieldAnswered,saveDatingProfile,numericRange} from './dating-data.js?v=0.4.12';

import {FRIENDSHIP_CHAPTERS,friendshipProfile,saveFriendshipProfile} from './friendship-data.js?v=0.4.12';
import {suggestionsFor,relatedSuggestions,answerParts,answerPatch,ownNote,notePatch,focusValue,focusPatch,rankPatch} from './connection-inputs.js?v=0.4.12';

const paths={
 heart:'M12 21S2 15 2 8a5 5 0 0 1 10-2A5 5 0 0 1 22 8c0 7-10 13-10 13Z',
 identity:'M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM2 22v-4a7 7 0 0 1 12-5M18 12v9m-4-5h8',
 love:'M12 8 9 5a3 3 0 0 0-5 3c0 4 8 8 8 8s8-4 8-8a3 3 0 0 0-5-3l-3 3ZM3 20h18M7 18v4m10-4v4',
 appearance:'M12 3C5 3 3 8 3 12s2 9 9 9 9-5 9-9-2-9-9-9ZM7 10h2m6 0h2M8 16q4 3 8 0M6 4 3 2m17 2 2-2',
 spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7ZM21 3v3m-2-1h4',
 emotional:'M4 20h5l3-3h4a6 6 0 0 0 6-6V8a6 6 0 0 0-6-6H8a6 6 0 0 0-6 6v3a6 6 0 0 0 2 5v4ZM7 9h10M7 13h6',
 intimacy:'M9 15a6 6 0 1 1 6-6M15 9a6 6 0 1 1-6 6M8 16l8-8',
 shield:'M12 2 3 6v7c0 5 9 9 9 9s9-4 9-9V6l-9-4ZM7 12l3 3 7-7',
 clock:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20ZM12 6v6l5 3',
 location:'M12 22s8-9 8-14A8 8 0 0 0 4 8c0 5 8 14 8 14ZM12 5a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',
 home:'m2 11 10-9 10 9M5 9v13h14V9M10 22v-8h4v8',
 signals:'M8 2h8v20H8V2ZM12 5v1m0 5v1m0 5v1'
};
function svgIcon(name){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.heart);p.setAttribute('fill','none');p.setAttribute('stroke','currentColor');p.setAttribute('stroke-width','1.7');p.setAttribute('stroke-linecap','round');p.setAttribute('stroke-linejoin','round');svg.append(p);return svg;}
function summary(chapter,draft){const filled=chapter.fields.find(f=>fieldAnswered(f,draft[f.key])||ownNote(draft,f.key).trim());if(!filled)return 'Tap to explore';if(!fieldAnswered(filled,draft[filled.key]))return ownNote(draft,filled.key);const v=draft[filled.key];if(filled.type==='love')return Object.entries(loveValue(v)).filter(([,n])=>n>=4).map(([key])=>LOVE_LANGUAGES.find(l=>l[0]===key)[1]).join(', ')||'Affection preferences saved';if(filled.type==='week')return listValue(v).length+' time windows';return filled.type==='choices'?listValue(v).join(', '):v;}

export function mountDating({panel,back,people,catchup,kind='dating'}){
 const friends=kind==='friends',chapters=friends?FRIENDSHIP_CHAPTERS:DATING_CHAPTERS,readProfile=friends?friendshipProfile:datingProfile,saveProfile=friends?saveFriendshipProfile:saveDatingProfile;
 panel.classList.add('dating-panel');let draft={...readProfile(readTravelProject())},saved=JSON.stringify(draft),chapterIndex=0,question=0;
 const dirty=()=>JSON.stringify(draft)!==saved;
 function leave(){if(!dirty()||confirm('Leave without saving your profile changes?')){panel.classList.remove('dating-panel');back();}}
 function save(status){try{writeTravelProject(p=>saveProfile(p,draft));draft={...readProfile(readTravelProject())};saved=JSON.stringify(draft);status.textContent='Saved in this browser.';status.dataset.error='false';}catch(e){status.textContent=e.message;status.dataset.error='true';}}
 function footer(container,{next,previous,focus=false}={}){const status=make('p','dating-status',dirty()?'Unsaved changes':'Only saved in this browser. Included in your Aura backup.');status.setAttribute('role','status');const foot=make('footer','dating-footer');if(previous){const b=button('‹',previous);b.setAttribute('aria-label','Previous question');foot.append(b);}if(next)foot.append(button('Next →',next));if(focus)foot.append(button('Priorities',()=>priorities(home)));foot.append(button('Save profile',()=>save(status),'dating-save'));container.append(status,foot);}
 function home(){header(panel,friends?'Friendships':'Dating',leave);panel.style.setProperty('--dating-colour',friends?'#438b79':'#b2547f');
  const completed=chapters.filter(c=>chapterProgress(c,draft)).length,hero=make('div','dating-hero'),art=make('div','dating-orbit');art.append(svgIcon(friends?'identity':'heart'));for(let i=0;i<chapters.length;i++){const dot=make('i');dot.style.setProperty('--angle',i*(360/chapters.length)+'deg');dot.style.background=chapters[i].colour;dot.style.opacity=chapterProgress(chapters[i],draft)?'1':'.22';art.append(dot);}const copy=make('div');copy.append(make('h2','',draft['Display name']||(friends?'Find your people':'Your connection map')),make('p','',`${completed} of ${chapters.length} areas explored`),make('small','',friends?'New friends, shared time and room to be you.':'Connection across many chapters of life.'));hero.append(art,copy);panel.append(hero);
  const tiles=make('div','dating-map');tiles.style.setProperty('--map-rows',Math.ceil(chapters.length/3));chapters.forEach((chapter,i)=>{const b=button('',()=>{chapterIndex=i;question=0;draw();},'dating-area');b.style.setProperty('--tile-colour',chapter.colour);const count=chapterProgress(chapter,draft);b.append(svgIcon(chapter.icon),make('strong','',chapter.short),make('small','',summary(chapter,draft)));const meter=make('span','dating-completion');meter.style.setProperty('--done',100*count/chapter.fields.length+'%');b.append(meter);b.setAttribute('aria-label',`${chapter.title}, ${count} of ${chapter.fields.length} explored`);tiles.append(b);});panel.append(tiles);
  const focus=focusValue(draft);tiles.querySelectorAll('button').forEach((b,i)=>{const rank=focus.order.indexOf(chapters[i].id);if(rank>=0)b.append(make('span','dating-rank-badge',String(rank+1)));});
  const nav=make('div','dating-links');nav.append(button('People & connections',()=>{if(!dirty()||confirm('Leave without saving your profile changes?')){panel.classList.remove('dating-panel');people();}}),button(friends?'Plan a catch-up':'Plan a date',()=>{if(!dirty()||confirm('Leave without saving your profile changes?')){panel.classList.remove('dating-panel');catchup();}}));panel.append(nav);footer(panel,{focus:true});
 }
 function draw(){const chapter=chapters[chapterIndex],field=chapter.fields[question];panel.style.setProperty('--dating-colour',chapter.colour);header(panel,chapter.title,home);
  const trail=make('div','dating-trail');chapter.fields.forEach((f,i)=>{const b=button(String(i+1),()=>{question=i;draw();});b.setAttribute('aria-label',f.label);b.setAttribute('aria-current',String(question===i));if(fieldAnswered(f,draft[f.key])||ownNote(draft,f.key).trim())b.dataset.filled='true';trail.append(b);});panel.append(trail);
  const sheet=make('section','dating-sheet');sheet.dataset.type=field.type;const emblem=make('div','dating-emblem');emblem.append(svgIcon(chapter.icon),make('span','',`${question+1} / ${chapter.fields.length}`));sheet.append(emblem,make('h2','',field.label),make('p','dating-help',field.hint||chapter.intro));
  emblem.append(button('Priorities',()=>priorities(draw),'dating-focus-link'));
  if(['choices','single'].includes(field.type))choices(sheet,field);else if(field.type==='scale')scale(sheet,field);else if(field.type==='love')love(sheet,field);else if(field.type==='week')week(sheet,field);else input(sheet,field);
  panel.append(sheet);
  footer(panel,{previous:question>0?()=>{question--;draw();}:null,next:()=>{if(question<chapter.fields.length-1){question++;draw();}else home();}});
  if(question===chapter.fields.length-1){const buttons=panel.querySelectorAll('.dating-footer button');buttons[buttons.length-2].textContent='Back to map';}
  let start;sheet.onpointerdown=e=>{if(e.target.closest('input,textarea,button,select'))return;start=framePoint(sheet,e);sheet.setPointerCapture(e.pointerId);};sheet.onpointerup=e=>{if(!start)return;const end=framePoint(sheet,e),dx=end.x-start.x,dy=end.y-start.y;start=null;if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.5){if(dx<0){if(question<chapter.fields.length-1){question++;draw();}else home();}else if(question>0){question--;draw();}}};sheet.onpointercancel=()=>start=null;
 }
 function mark(){const s=panel.querySelector('.dating-status');if(s){s.textContent='Unsaved changes';s.dataset.error='false';}}
 function set(key,v){draft[key]=v;mark();}
 function tick(){const n=make('span','dating-check','✓');n.setAttribute('aria-hidden','true');return n;}
 function patch(values){Object.assign(draft,values);mark();}
 function notes(parent,f){const label=make('label','dating-own'),text=make('textarea');label.append(make('span','','Your own words'));text.setAttribute('aria-label',f.label+' - your own words');text.placeholder='Add detail, exceptions or another answer…';text.value=ownNote(draft,f.key);text.oninput=()=>patch(notePatch(draft,f.key,text.value));label.append(text);parent.append(label);}
 function choices(parent,f){const wrap=make('div','dating-choices');const single=f.type==='single',selected=new Set(single?(draft[f.key]?[draft[f.key]]:[]):listValue(draft[f.key]));for(const option of f.options){const b=button('',()=>{const was=selected.has(option);if(single)selected.clear();if(was)selected.delete(option);else selected.add(option);set(f.key,single?([...selected][0]||''):JSON.stringify([...selected]));wrap.querySelectorAll('button').forEach((n,i)=>n.setAttribute('aria-pressed',String(selected.has(f.options[i]))));});b.append(tick(),make('span','',option));b.setAttribute('aria-pressed',String(selected.has(option)));wrap.append(b);}parent.append(wrap,make('p','dating-help',single?'Choose one, or write your own answer.':'Choose any that fit. Tap again to remove.'));notes(parent,f);}
 function scale(parent,f){const wrap=make('div','dating-spectrum'),out=make('output','',draft[f.key]||'Not set'),ends=make('div','dating-scale-ends'),rail=make('div','dating-scale-rail');ends.append(make('span','',f.options[0]),make('span','',f.options.at(-1)));const update=()=>{out.textContent=draft[f.key]||'Not set';rail.querySelectorAll('button').forEach((b,i)=>b.setAttribute('aria-pressed',String(draft[f.key]===f.options[i])));};f.options.forEach((o,i)=>{const b=button(String(i+1),()=>{set(f.key,draft[f.key]===o?'':o);update();});b.setAttribute('aria-label',o);rail.append(b);});out.setAttribute('aria-live','polite');wrap.append(ends,rail,out,make('small','','Tap a position. Tap it again to leave unset.'));parent.append(wrap);update();notes(parent,f);}
 function input(parent,f){
  if(f.type==='text'&&suggestionsFor(f.key).length){guided(parent,f);return;}
  const label=make('label','dating-input');const el=make(f.type==='number'?'input':'textarea');el.setAttribute('aria-label',f.label);el.value=draft[f.key]||'';el.placeholder=f.type==='number'?'Not set':'In your own words…';if(f.type==='number'){el.type='number';el.min=f.min;if(f.max!=null)el.max=f.max;el.step=f.unit==='years'?'1':'any';label.append(el,make('span','',f.unit));}else label.append(el);el.oninput=()=>set(f.key,el.value);parent.append(label);if(f.type==='number')parent.append(make('p','dating-help',`Optional · ${numericRange(f)}`));
 }
 function guided(parent,f){
  const parts=answerParts(draft,f.key),related=relatedSuggestions(draft,f.key),ideas=suggestionsFor(f.key).map(text=>({text,source:''}));let bank='ideas',page=0;
  parent.dataset.guided='true';const tabs=make('div','dating-answer-tabs'),wrap=make('div','dating-choices dating-suggestions'),pager=make('div','dating-idea-pages'),own=make('label','dating-own'),text=make('textarea');
  own.append(make('span','','Your own words'));text.value=parts.own;text.placeholder='Add detail or write something different…';text.setAttribute('aria-label',f.label+' - your own words');text.oninput=()=>{parts.own=text.value;patch(answerPatch(draft,f.key,parts));};own.append(text);
  const sync=()=>patch(answerPatch(draft,f.key,parts));
  function render(){tabs.replaceChildren();wrap.replaceChildren();pager.replaceChildren();
   for(const [id,label]of [['ideas','Ideas'],['related','Your answers'],['selected','Selected ('+parts.selected.length+')']]){if(id==='related'&&!related.length)continue;const b=button(label,()=>{bank=id;page=0;render();});b.setAttribute('aria-pressed',String(bank===id));tabs.append(b);}
   const options=bank==='ideas'?ideas:bank==='related'?related:parts.selected.map(text=>({text,source:''}));page=Math.min(page,Math.max(0,Math.ceil(options.length/6)-1));
   options.slice(page*6,page*6+6).forEach(({text,source})=>{const b=button('',()=>{const i=parts.selected.indexOf(text);if(i<0)parts.selected.push(text);else parts.selected.splice(i,1);sync();render();});b.append(tick(),make('span','',text));if(source)b.append(make('small','','From '+source));b.setAttribute('aria-pressed',String(parts.selected.includes(text)));wrap.append(b);});
   if(!options.length)wrap.append(make('p','dating-help','Nothing selected. Explore ideas or use your own words.'));
   if(options.length>6)for(let i=0;i<Math.ceil(options.length/6);i++){const b=button(String(i+1),()=>{page=i;render();});b.setAttribute('aria-label','Ideas group '+(i+1));b.setAttribute('aria-current',String(page===i));pager.append(b);}
  }
  parent.append(tabs,wrap,pager,own);render();
 }
 function priorities(returnTo){
  const c=chapters[chapterIndex],focus=focusValue(draft),value=focus.areas[c.id]||{},rank=focus.order.indexOf(c.id);header(panel,'Your priorities',returnTo);panel.style.setProperty('--dating-colour',c.colour);
  const nav=make('nav','dating-focus-areas');nav.setAttribute('aria-label','Choose an area to prioritise');chapters.forEach((area,i)=>{const b=button('',()=>{chapterIndex=i;priorities(returnTo===draw?home:returnTo);});b.append(svgIcon(area.icon));const n=focus.order.indexOf(area.id);if(n>=0)b.append(make('span','dating-rank-badge',String(n+1)));b.setAttribute('aria-label',area.title);b.setAttribute('aria-pressed',String(i===chapterIndex));b.style.setProperty('--tile-colour',area.colour);nav.append(b);});panel.append(nav);
  const sheet=make('section','dating-sheet dating-priorities');sheet.append(make('h2','',c.title));
  function segments(key,title,help,options){const group=make('section','dating-priority-group');group.append(make('strong','',title),make('small','',help));const rail=make('div','dating-priority-rail');options.forEach((label,i)=>{const b=button('',()=>{patch(focusPatch(draft,c.id,{[key]:value[key]===label?'':label}));priorities(returnTo);});const bars=make('span','dating-priority-bars');for(let n=0;n<3;n++){const bar=make('i');bar.dataset.on=String(n<=i);bars.append(bar);}b.append(bars,make('span','',label));b.setAttribute('aria-pressed',String(value[key]===label));rail.append(b);});group.append(rail);sheet.append(group);}
  segments('importance','Importance','How strongly does this area matter to you?',['Flexible','Important','Essential']);
  segments('urgency','Urgency','When would you like to give it attention?',['Later','Soon','Now']);
  const order=make('section','dating-priority-order'),summary=make('div');summary.append(make('strong','','Focus order'),make('small','',rank<0?'Unranked':`Priority ${rank+1} of ${focus.order.length}`));order.append(summary);
  if(rank<0)order.append(button('Add to focus order',()=>{patch(rankPatch(draft,c.id,focus.order.length));priorities(returnTo);}));else{const up=button('↑',()=>{patch(rankPatch(draft,c.id,rank-1));priorities(returnTo);}),down=button('↓',()=>{patch(rankPatch(draft,c.id,rank+1));priorities(returnTo);}),clear=button('×',()=>{patch(rankPatch(draft,c.id,null));priorities(returnTo);});up.disabled=rank===0;down.disabled=rank===focus.order.length-1;up.setAttribute('aria-label','Move priority earlier');down.setAttribute('aria-label','Move priority later');clear.setAttribute('aria-label','Remove priority rank');order.append(up,down,clear);}
  sheet.append(order,make('p','dating-help','Tap a selected scale to leave it unset. Rank areas to focus on, not people.'));
  panel.append(sheet);footer(panel);
 }
 function love(parent,f){const values=loveValue(draft[f.key]),wrap=make('div','dating-love');for(const [key,name,hint]of LOVE_LANGUAGES){const title=key==='gifts'&&f.key==='Love giving'?'Giving gifts':name;const row=make('div','dating-language'),top=make('div'),label=make('label','',title),out=make('output','',values[key]===undefined?'Not set':String(values[key])+' / 5'),slider=make('input');slider.type='range';slider.min=0;slider.max=5;slider.step=1;slider.value=values[key]??0;slider.id='dating-'+key;label.htmlFor=slider.id;slider.setAttribute('aria-label',title);slider.setAttribute('aria-valuetext',values[key]===undefined?'Not set':String(values[key])+' out of 5');const clear=button('×',()=>{delete values[key];set(f.key,JSON.stringify(values));slider.value=0;out.textContent='Not set';slider.setAttribute('aria-valuetext','Not set');});clear.setAttribute('aria-label','Clear '+title);top.append(label,out,clear);slider.oninput=()=>{values[key]=Number(slider.value);set(f.key,JSON.stringify(values));out.textContent=slider.value+' / 5';slider.setAttribute('aria-valuetext',slider.value+' out of 5');};row.append(top,make('small','',hint),slider);wrap.append(row);}parent.append(wrap,make('p','dating-help','0 = not important to me · 5 = very important. Each can matter differently.'));}
 function week(parent,f){const selected=new Set(listValue(draft[f.key])),wrap=make('div','dating-week');wrap.append(make('span'));DAYS.forEach(d=>wrap.append(make('strong','',d)));DAY_PARTS.forEach(part=>{wrap.append(make('span','',part));DAYS.forEach(day=>{const key=day+' '+part,b=button('',()=>{selected.has(key)?selected.delete(key):selected.add(key);set(f.key,JSON.stringify([...selected]));b.setAttribute('aria-pressed',String(selected.has(key)));b.textContent=selected.has(key)?'✓':'·';});b.setAttribute('aria-label',key);b.setAttribute('aria-pressed',String(selected.has(key)));b.textContent=selected.has(key)?'✓':'·';wrap.append(b);});});parent.append(wrap,make('p','dating-help','Selected windows are highlighted. Set exact dates through the planning button on your map.'));}
 home();return {home};
}
