import {loadMap} from './market-map.js?v=0.3.7';
import {EARTH,EARTH_WIDE,earthRows,filterEarth,clusterEarth,personalEarthRows,importEarthPoints,saveEarthPoints} from './earth-data.js?v=0.3.7';
import {readTravelProject,writeTravelProject,CELESTIAL} from './travel-data.js?v=0.3.7';
import {CROWN} from './original-routes.js?v=0.3.7';
import {framePoint} from './frame-display.js?v=0.3.7';
const make=(tag,cls='',text)=>{const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(label,fn)=>{const b=make('button','',label);b.type='button';b.onclick=fn;return b;};

let snapshot,viewState;
function earthSnapshot(){return snapshot||(snapshot=fetch('assets/earth/manifest.json?v=0.3.7').then(async response=>{if(!response.ok)throw Error('Earth layer list could not load.');const metadata=await response.json();const data=await Promise.all(metadata.layers.map(async layer=>{const r=await fetch(layer.data);if(!r.ok)throw Error(layer.label+' could not load.');return earthRows(layer,await r.json());}));return {metadata,records:data.flat()};}).catch(e=>{snapshot=null;throw e;}));}
export function mountEarth({page,screen,go}){
 for(const c of page.controls)if(c.controlTypeID!=='StatusBar(Android)')screen.querySelector(`[data-source-control="${c.controlID}"]`)?.setAttribute('hidden','');
 let disposed=false,map,L,markers,metadata,records=[],found=[],offset=0,pinning=false,filterAffinity=viewState?.filterAffinity??true,selected=new Set(),query=viewState?.query||'';
 const panel=make('section','earth-panel'+(page.width>page.height?' earth-wide':''));panel.style.width=(page.width-16)+'px';panel.style.height=(page.height-32)+'px';panel.setAttribute('aria-label','Crown Earth map');screen.append(panel);
 const head=make('header');head.append(make('h2','','Earth'),button('Stars',()=>go(CELESTIAL)),button(page.id===EARTH?'Wide':'Tall',()=>go(page.id===EARTH?EARTH_WIDE:EARTH)),button('Crown',()=>go(CROWN)));panel.append(head);
 const search=make('input');search.type='search';search.value=query;search.placeholder='Find any name or place';search.setAttribute('aria-label',search.placeholder);panel.append(search);
 const status=make('p','earth-status','Loading the eight Horn Torus layers…');status.setAttribute('role','status');panel.append(status);
 const canvas=make('div','earth-canvas');canvas.setAttribute('aria-label','Interactive Earth map');panel.append(canvas);
 const results=make('div','earth-results'),pager=make('nav','earth-pager'),prev=button('‹',()=>{offset-=2;list();}),next=button('›',()=>{offset+=2;list();}),count=make('span');prev.setAttribute('aria-label','Previous places');next.setAttribute('aria-label','More places');pager.append(prev,count,next);const listrow=make('div','earth-listrow');listrow.append(results,pager);panel.append(listrow);
 const foot=make('footer'),layersButton=button('Layers',layers),pin=button('Drop pin',()=>{pinning=!pinning;pin.setAttribute('aria-pressed',String(pinning));status.textContent=pinning?'Tap the map to place a pin.':summary();}),file=make('input');file.type='file';file.accept='.geojson,.json,.csv';file.hidden=true;file.setAttribute('aria-label','Import map points');foot.append(layersButton,pin,button('Import',()=>file.click()),button('Fit',fit));panel.append(foot,file);
 const drawer=make('section','earth-drawer');drawer.hidden=true;panel.append(drawer);
 function summary(){return `${found.length.toLocaleString()} matching places · ${metadata?.total.toLocaleString()||'0'} source records`;}
 function popup(r){const n=make('div');n.append(make('strong','',r.name),make('p','',r.detail));const meta=metadata.layers.find(x=>x.id===r.layer);n.append(make('small','',meta?`${meta.label} · ${meta.statusLabel}`:'My saved place'));if(meta){n.append(make('p','',meta.coordinateBasis));}if(r.url){const a=make('a','','Source');a.href=r.url;a.target='_blank';a.rel='noopener';n.append(a);}return n;}
 function show(r){map.setView([r.lat,r.lng],Math.max(12,map.getZoom()));L.popup({maxWidth:220}).setLatLng([r.lat,r.lng]).setContent(popup(r)).openOn(map);}
 function list(){offset=Math.max(0,Math.min(offset,Math.max(0,Math.floor((found.length-1)/2)*2)));results.replaceChildren();for(const r of found.slice(offset,offset+2)){const b=button(r.name,()=>show(r));b.title=r.detail;results.append(b);}if(!found.length)results.append(make('small','','No matches. Choose layers or change the search.'));count.textContent=found.length?`${offset+1}-${Math.min(offset+2,found.length)}`:'0';prev.disabled=!offset;next.disabled=offset+2>=found.length;}
 function draw(){if(!map)return;markers.clearLayers();const w=canvas.clientWidth,h=canvas.clientHeight;
  const clusters=clusterEarth(found,r=>{const p=map.latLngToContainerPoint([r.lat,r.lng]);return p.x>=-20&&p.x<=w+20&&p.y>=-20&&p.y<=h+20?p:null;});
  for(const g of clusters){const r=g.first,b=L.circleMarker([r.lat,r.lng],{radius:g.count>1?Math.min(17,7+Math.log10(g.count)*3):5,color:'#fff',weight:1,fillColor:r.colour||'#547c94',fillOpacity:.85}).addTo(markers);if(g.count>1){b.bindTooltip(String(g.count),{permanent:true,direction:'center',className:'earth-cluster'});b.on('click',e=>{L.DomEvent.stopPropagation(e.originalEvent);if(pinning)return;if(map.getZoom()<18)map.setView([r.lat,r.lng],map.getZoom()+2);else b.bindPopup(`${g.count} nearby places. Use search and the place list to inspect individual records.`).openPopup();});}else b.bindPopup(()=>popup(r));}
 }
 function refresh(){if(!metadata)return;found=filterEarth([...records,...personalEarthRows(readTravelProject())],{layers:selected,query,filterAffinity});offset=0;status.textContent=summary();list();draw();}
 function fit(){if(!map)return;if(found.length)map.fitBounds(L.latLngBounds(found.map(r=>[r.lat,r.lng])),{padding:[20,20],maxZoom:14});}
 function heading(text){drawer.replaceChildren();const h=make('header');h.append(make('h3','',text),button('Done',()=>drawer.hidden=true));drawer.append(h);drawer.hidden=false;}
 function layers(){if(!metadata)return;heading('Map layers');const grid=make('div','earth-layers');for(const m of [...metadata.layers,{id:'personal',label:'My pins & imports'}]){const row=make('label'),check=make('input');check.type='checkbox';check.checked=selected.has(m.id);check.onchange=()=>{if(check.checked)selected.add(m.id);else selected.delete(m.id);refresh();};row.append(check,make('span','',m.label));grid.append(row);}drawer.append(grid);
  const match=make('label','earth-affinity'),check=make('input');check.type='checkbox';check.checked=filterAffinity;check.onchange=()=>{filterAffinity=check.checked;refresh();};match.append(check,make('span','','Affinity: matching names only'));drawer.append(match,button('Sources and accuracy',sources));
 }
 function sources(){heading('Sources');const select=make('select');select.setAttribute('aria-label','Map source details');for(const m of metadata.layers){const o=make('option','',m.label);o.value=m.id;select.append(o);}const details=make('div','earth-source-detail');const update=()=>{const m=metadata.layers.find(m=>m.id===select.value);details.replaceChildren(make('p','',`${m.mappedCount.toLocaleString()} points · ${m.statusLabel}`),make('p','',m.warning),make('p','',m.rightsNote||m.coordinateBasis));const a=make('a','','Original Horn Torus map');a.href=metadata.source;a.target='_blank';a.rel='noopener';details.append(a);};select.onchange=update;drawer.append(select,details);update();}
 function pinForm(latlng){pinning=false;pin.setAttribute('aria-pressed','false');heading('Save this place');const name=make('input');name.placeholder='Place name';name.setAttribute('aria-label','Place name');const notes=make('input');notes.placeholder='Notes (optional)';notes.setAttribute('aria-label','Pin notes');drawer.append(name,notes,make('p','',`${latlng.lat.toFixed(5)}, ${latlng.lng.toFixed(5)}`),button('Save pin',()=>{try{writeTravelProject(p=>saveEarthPoints(p,[{name:name.value,lat:latlng.lat,lng:latlng.lng,detail:notes.value}]));selected.add('personal');drawer.hidden=true;refresh();}catch(e){status.textContent=e.message;}}));name.focus();}
 file.onchange=async()=>{const f=file.files[0];if(!f)return;try{const points=importEarthPoints(await f.text(),f.name);if(disposed)return;if(!points.length)throw Error('The file has no points.');heading(`Import ${points.length} points`);drawer.append(make('p','',`${f.name}. These points will be added to My Earth places in your Aura tables.`),button('Add these points',()=>{try{writeTravelProject(p=>saveEarthPoints(p,points,f.name));selected.add('personal');drawer.hidden=true;refresh();}catch(e){status.textContent=e.message;}}));}catch(e){status.textContent=e.message;}file.value='';};
 let delay;search.oninput=()=>{clearTimeout(delay);delay=setTimeout(()=>{query=search.value;refresh();},180);};
 // Leaflet's built-in dragging assumes an unscaled, upright viewport. Use frame
 // coordinates so drag and pin placement also work in the original rotated layouts.
 let drag=null,moved=false;
 const down=e=>{if(!map||e.target.closest('button,a,input,.leaflet-control,.leaflet-popup'))return;drag=framePoint(canvas,e);moved=false;canvas.setPointerCapture(e.pointerId);};
 const move=e=>{if(!drag)return;const p=framePoint(canvas,e);if(Math.hypot(p.x-drag.x,p.y-drag.y)>3){moved=true;map.panBy([drag.x-p.x,drag.y-p.y],{animate:false});drag=p;}};
 const up=e=>{if(!drag)return;const p=framePoint(canvas,e);if(pinning&&!moved){const ll=map.containerPointToLatLng([p.x,p.y]).wrap();if(Math.abs(ll.lat)<=90)pinForm(ll);}drag=null;};
 canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>drag=null);
 canvas.addEventListener('wheel',e=>{if(!map)return;e.preventDefault();map.setZoom(map.getZoom()+(e.deltaY<0?1:-1));},{passive:false});
 Promise.all([loadMap(),earthSnapshot()]).then(([lib,loaded])=>{if(disposed)return;L=lib;metadata=loaded.metadata;records=loaded.records;selected=new Set(viewState?.selected||[...metadata.layers.map(m=>m.id),'personal']);
  map=L.map(canvas,{preferCanvas:true,dragging:false,scrollWheelZoom:false,touchZoom:false,doubleClickZoom:false,boxZoom:false,minZoom:1,maxZoom:19,maxBounds:[[-85,-180],[85,180]]}).setView(viewState?.center||[0,0],viewState?.zoom||1);map.mouseEventToContainerPoint=e=>{const p=framePoint(canvas,e);return L.point(p.x,p.y);};
  L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);markers=L.layerGroup().addTo(map);map.on('moveend',draw);map.invalidateSize();refresh();
 }).catch(e=>{if(!disposed)status.textContent=e.message;});
 return {resize(){map?.invalidateSize();},dispose(){disposed=true;clearTimeout(delay);if(map)viewState={center:map.getCenter(),zoom:map.getZoom(),query,selected:[...selected],filterAffinity};map?.remove();}};
}
