import {rows} from './local-tools.js?v=0.4.11';
import {savePreferenceProfile} from './dating-data.js?v=0.4.11';
const choices=(key,label,options,hint='')=>({key,label,type:'choices',options:options.split('|'),hint});
const words=(key,label,hint='')=>({key,label,type:'text',hint});
export const FRIENDSHIP_CHAPTERS=[
 {id:'new',title:'Making new friends',short:'New friendships',colour:'#438b79',icon:'identity',intro:'Explore who you would like to meet and how to begin.',fields:[
  choices('Friendship hopes','What friendships would you like to make?','Close friends|Activity mates|Local friends|Creative collaborators|Travel companions|Study buddies|Online friends|Community circles|Intergenerational friends|New to the area'),words('Hopes','What is missing or would feel good in your social life?'),choices('Meeting routes','How would you like to meet people?','Shared activities|Classes|Volunteering|Community events|Friends of friends|Local groups|Online communities|Interest clubs|Small gatherings|One-to-one introductions'),words('First step','What would make it easier to say hello?'),words('Invitation','What could you invite someone to do with you?')]},
 {id:'qualities',title:'Qualities & values',short:'Qualities',colour:'#728943',icon:'spark',intro:'What you bring, what you appreciate and what makes friendship work.',fields:[
  choices('Friend qualities','What qualities do you value in a friend?','Kindness|Humour|Honesty|Reliability|Curiosity|Patience|Creativity|Loyalty|Independence|Empathy|Adventure|Mutual effort'),choices('My qualities','What do you bring to a friendship?','Good listening|Practical help|Humour|Encouragement|Ideas|Hospitality|Shared knowledge|Calm|Energy|Consistency|Creativity|Perspective'),words('Values','What values would you like to share?'),words('Friendship meaning','What does being a good friend mean to you?')]},
 {id:'openness',title:'Openness & differences',short:'Open mindedness',colour:'#5b7fba',icon:'emotional',intro:'Name the differences you enjoy, the things you are curious about and the pace you need.',fields:[
  choices('Differences welcome','What differences are you open to exploring?','Cultures|Languages|Generations|Worldviews|Faiths|Personalities|Neurotypes|Abilities|Lifestyles|Interests|Backgrounds|Life experiences'),words('Curious about','What would you like to understand through new friendships?'),words('Respectful disagreement','What does respectful disagreement look like to you?'),words('Openness limits','Where do you need common ground?'),words('Pace','What helps you stay open without feeling pushed?')]},
 {id:'boundaries',title:'Hard no’s & boundaries',short:'Hard no’s',colour:'#b76369',icon:'shield',intro:'Your boundaries help you choose friendships that feel right.',fields:[
  choices('Hard no topics','What behaviour is a hard no for you?','Pressure|Cruelty|Dishonesty|Discrimination|Boundary pushing|Manipulation|Gossip about private matters|Repeated unreliability|One-sided demands|Unwanted romantic attention'),words('Hard no details','Your hard no’s, in your own words'),words('Boundaries','What boundaries should friends understand?','Contact, lending money, substances, touch, privacy or your own needs.'),words('Needs discussion','What needs a conversation rather than an automatic no?'),words('Repair','What would repair trust, and when would you step away?')]},
 {id:'time',title:'Time & social energy',short:'Time & energy',colour:'#508e9b',icon:'clock',intro:'Make room for friendship at a rhythm you can sustain.',fields:[
  {key:'Weekly availability',label:'When do you usually have time?',type:'week',hint:'Tap times that usually suit you. Exact catch-ups are planned separately.'}, {key:'Hours for friends',label:'Time you would like for friends each week',type:'number',min:0,max:168,unit:'hours'},words('Availability','What affects your available time?'),choices('Contact rhythm','What contact rhythm works for you?','Most days|A few times a week|Weekly|Monthly|Occasional but meaningful|Flexible'),choices('Social energy','What kinds of social time suit your energy?','One-to-one|Small groups|Larger gatherings|Quiet company|Lively activities|Short catch-ups|Long conversations|Changes day to day'),words('Recovery time','What helps you recharge or say you need space?')]},
 {id:'activities',title:'Shared interests',short:'Do things together',colour:'#ac7c3e',icon:'home',intro:'Find something enjoyable to do together, not just a name in a contacts list.',fields:[
  choices('Shared interests','What would you enjoy sharing?','Nature|Food & cooking|Arts|Music|Sport|Games|Learning|Making things|Travel|Volunteering|Spirituality|Conversation'),words('Activities','Specific activities or interests you would like to share'),words('Try something new','What would you like to try with a new friend?'),words('Offer to share','What could you teach, host or help with?'),words('Budget and access','What would make activities affordable and accessible?')]},
 {id:'place',title:'Place & connection',short:'Where to meet',colour:'#668453',icon:'location',intro:'Connect in places and ways that fit your life.',fields:[
  words('Based near','What town, city or region are you near?'),{key:'Travel distance',label:'How far would you usually travel to meet?',type:'number',min:0,max:20000,unit:'km'},choices('Meeting options','Where would you like to connect?','Nearby|Online|Outdoors|Community spaces|Shared classes|Cafés|Meet halfway|While travelling'),words('Access needs','Any transport, access or sensory preferences?'),words('Local ideas','Groups, places or events you would like to explore')]},
 {id:'care',title:'Communication & care',short:'Care & contact',colour:'#8d70ab',icon:'love',intro:'Make mutual care practical without assuming unlimited availability.',fields:[
  choices('Communication','How do you like to keep in touch?','Messages|Voice notes|Phone calls|Video calls|In person|Shared activities|Group chats|Quiet company'),words('Support offered','What kind of support can you offer?'),words('Support wanted','What kind of support would you appreciate?'),words('Check-ins','How should a friend check in if you go quiet?'),words('Mutual effort','How would you like effort, invitations and care to be shared?')]},
 {id:'signals',title:'Signals & next steps',short:'Signals',colour:'#b37a55',icon:'signals',intro:'Recognise a promising friendship and choose a small next step.',fields:[
  words('Green signals','What makes a new friendship feel promising?'),words('Amber signals','What makes you slow down and learn more?'),words('Private details','What needs trust before you share it?'),words('Next step','What is one thing you would like to do to meet new people?'),words('Stay connected','What would help turn a good meeting into an ongoing friendship?')]}
];
export const friendshipProfile=project=>rows(project,'aura-preferences').find(r=>r.id==='social-friends')||{};
export const saveFriendshipProfile=(project,fields)=>savePreferenceProfile(project,fields,FRIENDSHIP_CHAPTERS,'social-friends','friends');
