import {LIFE_SECTIONS,SOCIAL_HOME,entriesFor,categoryFor,birthdayFor,rowRef,progressOf,saveLife,importLifePreview,importLife} from './life-data.js?v=0.4.8';
import {readTravelProject,writeTravelProject} from './travel-data.js?v=0.4.8';
import {framePoint} from './frame-display.js?v=0.4.8';
const make=(tag,cls='',text)=>{const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const button=(text,fn,cls='')=>{const n=make('button',cls,text);n.type='button';n.onclick=fn;return n;};
const paths={people:'M8 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M1 22v-3a7 7 0 0 1 14 0v3M17 5a3 3 0 0 1 0 6M18 15a5 5 0 0 1 5 5v2',heart:'M12 21S1 14 1 7a6 6 0 0 1 11-3A6 6 0 0 1 23 7c0 7-11 14-11 14Z',compass:'M12 1a11 11 0 1 0 0 22 11 11 0 0 0 0-22M16 7l-3 7-6 3 3-7Z',spark:'M12 1l3 7 8 4-8 3-3 8-4-8-7-3 7-4Z',sun:'M12 6a6 6 0 1 0 0 12 6 6 0 0 0 0-12M12 0v3M12 21v3M0 12h3M21 12h3M3 3l2 2M19 19l2 2M3 21l2-2M19 5l2-2',celebrate:'M2 22l5-15 10 10ZM13 2l1 4M19 4l-2 3M21 10l-4 1M8 2l2 2',book:'M12 5C7 1 1 3 1 3v17s6-2 11 2c5-4 11-2 11-2V3S17 1 12 5v17',place:'M12 23S3 13 3 9a9 9 0 0 1 18 0c0 4-9 14-9 14ZM12 5a4 4 0 1 0 0 8 4 4 0 0 0 0-8',build:'M2 7l10-5 10 5v12l-10 4-10-4ZM2 7l10 5 10-5M12 12v11',home:'M1 11L12 1l11 10M4 9v14h16V9M9 23v-8h6v8',steps:'M1 23v-7h7V9h7V2h8M18 7l5-5M18 2h5v5',talk:'M3 3h18v14H9l-6 5ZM7 7h10M7 12h7',plus:'M12 3v18M3 12h18'};
function icon(name){const n=document.createElementNS('http://www.w3.org/2000/svg','svg');n.setAttribute('viewBox','0 0 24 24');n.setAttribute('aria-hidden','true');const p=document.createElementNS(n.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.spark);n.append(p);return n;}
const field=(key,label=key,type='text',options=null)=>({key,label,type,options});
function fieldPages(s,occasion){
 if(s.key==='family'&&!occasion)return [
  ['Person',[field('Title','Name'),field('Relationship','Relationship to you','select',['Parent','Child','Sibling','Partner','Grandparent','Grandchild','Extended family','Chosen family','Friend','Mentor','Neighbour','Other']),field('Shared context','How we connect'),field('Pronouns')]],
  ['Connections',[field('Connected person','Connect to another person','person'),field('Connection',"This person's relationship to the linked person",'select',['Parent of','Child of','Sibling of','Partner of','Relative of','Friend of','Supports']),field('Traditions','Shared traditions or activities','textarea')]],
  ['Dates',[field('Birthday','Birthday (optional)','date'),field('Important date','Another key date or occasion'),field('Reminder minutes','Birthday reminder lead time (minutes)','number'),field('Contact rhythm','When would you like to catch up?')]],
  ['Details',[field('Contact','Contact details'),field('Place','Location'),field('Notes','Memories, interests and practical notes','textarea'),field('Asset','Photo, album or reference link','url')]]
 ];
 if(occasion)return [
  ['Occasion',[field('Title','Occasion name'),field('People','Who is involved?'),field('Meaning','What does this mark?','textarea')]],
  ['When',[field('Date','Date','date'),field('Time','Time','time'),field('Place','Location'),field('Reminder minutes','Reminder lead time (minutes)','number')]],
  ['Prepare',[field('Traditions','Rituals and traditions','textarea'),field('Next action','Next practical step'),field('Notes','Preparations and things to bring','textarea')]],
  ['Details',[field('Status','Status','select',['Idea','Planned','Active','Done','Paused']),field('Asset','Reference link','url'),field('Instructions','Instructions for a future assistant','textarea')]]
 ];
 if(s.key==='favourites')return [
  ['Favourite',[field('Title','What do you love?'),field('Type','Type or format'),field('Creator','Creator, author or artist'),field('What resonates','Why does it resonate?','textarea')]],
  ['Experience',[field('Context','Mood, situation or company'),field('Possible use','How could this help your everyday life?','textarea'),field('People','Who would you share it with?')]],
  ['Details',[field('Place','Place or setting'),field('Asset','Website, playlist or reference link','url'),field('Notes','Memories and details','textarea')]],
  ['Revisit',[field('Review date','Revisit on','date'),field('Tags','Tags, separated by commas'),field('Instructions','How should a future assistant use this preference?','textarea')]]
 ];
 return [
  ['Idea',[field('Title',s.key==='wishes'?'What do you wish for?':s.key==='bucket'?'What would you love to experience?':'What do you want to achieve?'),field('Why it matters','Why it matters','textarea'),field('Priority','Priority','select',['Someday','Interested','Important','Next up']),field('Status','Status','select',['Idea','Planned','Active','Done','Paused'])]],
  ['Plan',[field('Next action','Smallest next step'),field('Steps','Steps or milestones (one per line)','textarea'),field('People','People to involve'),field('Place','Location or destination')]],
  ['Timing',[field('Target date','Target date (optional)','date'),field('Season','Preferred season or time window'),field('Reminder minutes','Reminder lead time (minutes)','number'),field('Budget','Budget','number'),field('Currency','Currency, for example AUD')]],
  ['Progress',[field('Value','Progress so far','number'),field('Target','Target amount','number'),field('Unit','Unit, for example sessions or dollars'),field('Notes','Progress notes, obstacles or memories','textarea')]],
  ['Connections',[field('Asset','Reference or inspiration link','url'),field('Resources','Resources and help needed','textarea'),field('Instructions','Instructions for a future assistant','textarea')]]
 ];
}
function download(name,type,text){const url=URL.createObjectURL(new Blob([text],{type})),a=make('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const csvText=rows=>rows.map(row=>row.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\r\n');
export function mountLife({screen,go,section:s}){
 for(const c of screen.children)c.hidden=true;
 const panel=make('section','life-panel life-'+s.key);screen.append(panel);
 let project,category='',pageIndex=0,query='',editing=null,draft=null,tab=0,dirty=false,mode='home',pending=null;
 const status=make('p','life-status');status.setAttribute('role','status');
 function safe(fn){try{fn();}catch(e){status.textContent=e.message;}}
 try{project=readTravelProject();}catch(e){panel.append(make('h1','','Your saved data could not be opened'),make('p','',e.message),button('Back',()=>go(SOCIAL_HOME)));return {resize(){},dispose(){}};}
 const rows=()=>entriesFor(project,s.key);
 function header(title,back){const h=make('header','life-header'),b=button('‹',back);b.setAttribute('aria-label','Back');h.append(b,make('h1','',title));panel.append(h);}
 function nav(){const n=make('nav','life-collection-nav');n.setAttribute('aria-label','Life collections');for(const section of LIFE_SECTIONS){const b=button('',()=>leave(()=>section.key===s.key?home():go(section.id)));b.title=section.title;b.setAttribute('aria-label',section.title);b.setAttribute('aria-current',section.key===s.key?'page':'false');const img=make('img');img.src='assets/mockplus/'+section.image;img.alt='';b.append(img);n.append(b);}panel.append(n);}
 function leave(fn){if(!dirty){fn();return;}panel.replaceChildren();header('Keep your changes?',()=>drawEditor());panel.append(make('p','life-intro','This entry has not been saved yet.'));const actions=make('div','life-confirm');actions.append(button('Continue editing',drawEditor),button('Save changes',()=>safe(()=>{persist();fn();}),'life-primary'),button('Discard changes',()=>{dirty=false;fn();}));panel.append(actions,status);}
 function base(title,back){panel.replaceChildren();header(title,back);status.textContent='';}
 function hero(title,subtitle,kind=''){const h=make('div','life-hero'),art=make('div','life-hero-art');if(kind)art.append(icon(kind));else{const img=make('img');img.src='assets/mockplus/'+s.image;img.alt='';art.append(img);}const copy=make('div');copy.append(make('strong','',title),make('p','',subtitle));h.append(art,copy);panel.append(h);return h;}
 function home(){mode='home';dirty=false;base(s.title,()=>go(SOCIAL_HOME));hero(s.intro,`${rows().length} saved ${s.key==='family'?'people and occasions':'entries'} • choose a category`);
  const grid=make('div','life-categories');for(const g of [...s.groups,{name:'Other',icon:'plus',prompts:[]}]){const count=rows().filter(r=>categoryFor(r,s)===g.name).length,b=button('',()=>{category=g.name;pageIndex=0;query='';list();},'life-category');b.append(icon(g.icon),make('strong','',g.name),make('small','',count?`${count} saved`:'Explore & add'));grid.append(b);}panel.append(grid);
  const tools=make('div','life-tools');tools.append(button('All entries',()=>{category='';pageIndex=0;query='';list();}));if(s.key==='family')tools.append(button('Connections',()=>connections()));tools.append(button('Import / export',toolsPage));panel.append(tools,status);nav();
 }
 function group(){return s.groups.find(g=>g.name===category)||{name:category||'All entries',icon:'spark',prompts:[]};}
 function draftFromIdea(title){if(s.key==='family'&&category!==s.groups[1].name){const relationships={'Add a parent':'Parent','Add a sibling':'Sibling','Add a child':'Child','Add a partner':'Partner','Add chosen family':'Chosen family','Add a grandparent':'Grandparent','Add a trusted friend':'Friend','Add a mentor':'Mentor','Add a neighbour':'Neighbour'};return {Title:'',Relationship:relationships[title]||'',Category:category,...(relationships[title]?{}:{'Shared context':title})};}return {Title:title,Category:category};}
 function cards(){const saved=rows().filter(r=>!category||categoryFor(r,s)===category),g=group();const items=saved.map(r=>({row:r,title:r.Title,subtitle:s.key==='family'?r.recommendation==='ceremonies'?(r.Date||'Family occasion'):(r.Relationship||'Person'):r.Status||r.Type||r.Category||'Saved',saved:true}));for(const prompt of g.prompts)if(!saved.some(r=>r.Title?.toLowerCase()===prompt.toLowerCase()))items.push({title:prompt,subtitle:'Idea to personalise',saved:false});return items.filter(r=>[r.title,r.subtitle,r.row?.Notes].join(' ').toLowerCase().includes(query.toLowerCase()));}
 function list(){mode='list';base(category||s.title,home);const g=group();hero(s.key==='family'?'People, links & memories':s.key==='favourites'?'Keep what speaks to you':s.key==='wishes'?'Imagine it. Give it a first step.':s.key==='bucket'?'Someday starts with an idea':'One step closer',category?'Choose an idea or open a saved entry.':'Your saved entries across every category.',g.icon);
  const search=make('input','life-search');search.type='search';search.placeholder='Find an entry or idea';search.setAttribute('aria-label','Find an entry or idea');search.value=query;search.oninput=()=>{query=search.value;pageIndex=0;renderCards();};panel.append(search);
  const grid=make('div','life-entries'),pager=make('div','life-pager');panel.append(grid,pager);function renderCards(){grid.replaceChildren();pager.replaceChildren();const items=cards(),total=Math.max(1,Math.ceil(items.length/6));pageIndex=Math.min(pageIndex,total-1);for(const item of items.slice(pageIndex*6,pageIndex*6+6)){const b=button('',()=>openEditor(item.row||null,item.saved?null:draftFromIdea(item.title)),'life-entry '+(item.saved?'is-saved':'is-idea'));b.append(icon(item.saved&&s.key==='family'?'people':g.icon),make('strong','',item.title),make('small','',item.subtitle));if(item.saved){const p=progressOf(item.row);if(p!==null){const meter=make('progress');meter.max=100;meter.value=p;meter.setAttribute('aria-label','Progress');b.append(meter,make('small','',`${Math.round(p)}%`));}}grid.append(b);}if(!items.length)grid.append(make('p','life-empty',query?'No matches. Try another word.':'Start your own entry below.'));const prev=button('‹',()=>{pageIndex--;renderCards();}),next=button('›',()=>{pageIndex++;renderCards();});prev.setAttribute('aria-label','Previous entries');next.setAttribute('aria-label','Next entries');prev.disabled=pageIndex===0;next.disabled=pageIndex===total-1;pager.append(prev,make('span','',`${pageIndex+1} / ${total}`),next);}
  renderCards();swipe(grid,delta=>{const max=Math.max(0,Math.ceil(cards().length/6)-1);pageIndex=Math.max(0,Math.min(max,pageIndex+delta));renderCards();});
  const foot=make('div','life-tools');foot.append(button('+ Add your own',()=>openEditor(null,{Category:category||'Other'}),'life-primary'),button('Import / export',toolsPage));panel.append(foot,status);nav();
 }
 function openEditor(row,initial){editing=row;draft=row?{...row,Category:row.Category||categoryFor(row,s)}:{...initial};for(const key of ['tableId','id','recommendation'])delete draft[key];if(row&&s.key==='family')draft.Birthday=birthdayFor(project,row)?.Date||'';tab=0;dirty=false;drawEditor();}
 function persist(){const existing=editing;project=writeTravelProject(p=>saveLife(p,s.key,draft,existing));if(!existing){const candidates=rows();editing=candidates.at(-1);}else editing=rows().find(r=>r.id===existing.id&&r.tableId===existing.tableId);dirty=false;}
 function drawEditor(){mode='edit';base(editing?'Edit entry':'Make it yours',()=>leave(list));const occasion=s.key==='family'&&(draft.Category===s.groups[1].name||editing?.recommendation==='ceremonies'),pages=fieldPages(s,occasion);tab=Math.min(tab,pages.length-1);
  const visual=hero(draft.Title||group().name,s.key==='family'?(draft.Relationship||'Add the connections that matter'):draft['Next action']||'Your details become reusable Aura data.',occasion?'celebrate':group().icon);
  if(s.key==='family'&&!occasion){const linked=rows().find(r=>rowRef(r)===draft['Connected person']);if(linked){const line=make('div','life-connection');line.append(make('span','',draft.Title||'This person'),make('small','',(draft.Connection||'Connected to')+' →'),make('span','',linked.Title));panel.append(line);}}
  if(!occasion&&s.key!=='family'&&s.key!=='favourites'){const percent=progressOf(draft);if(percent!==null){const meter=make('progress');meter.max=100;meter.value=percent;meter.setAttribute('aria-label','Goal progress');visual.append(meter);}}
  const tabs=make('nav','life-tabs');tabs.setAttribute('aria-label','Entry details');pages.forEach(([name],i)=>{const b=button(name,()=>{tab=i;drawEditor();});b.setAttribute('aria-current',tab===i?'step':'false');tabs.append(b);});panel.append(tabs);
  const form=make('form','life-form');form.id='life-form';for(const f of pages[tab][1]){const label=make('label'),caption=make('span','',f.label);let input;
   if(f.type==='select'||f.type==='person'){input=make('select');const choices=f.type==='person'?rows().filter(r=>r.recommendation==='relationships'&&(!editing||rowRef(r)!==rowRef(editing))).map(r=>[rowRef(r),r.Title]):f.options.map(x=>[x,x]);if(draft[f.key]&&!choices.some(x=>x[0]===draft[f.key]))choices.push([draft[f.key],draft[f.key]]);for(const [value,text]of [['','Choose if useful'],...choices]){const o=make('option','',text);o.value=value;input.append(o);}}
   else if(f.type==='textarea'){input=make('textarea');input.rows=2;}else{input=make('input');input.type=f.type;if(f.type==='number'){input.min='0';input.step='any';input.inputMode='decimal';}}
   input.value=draft[f.key]||'';input.setAttribute('aria-label',f.label);input.oninput=()=>{draft[f.key]=input.value;dirty=true;status.textContent='Unsaved changes';};label.append(caption,input);form.append(label);
  }
  if(tab===0){const label=make('label'),select=make('select');select.setAttribute('aria-label','Category');const categories=[...s.groups.filter(g=>!editing||s.key!=='family'||(editing.recommendation==='ceremonies')===(g.name===s.groups[1].name)).map(g=>g.name),...(editing?.recommendation==='ceremonies'?[]:['Other'])];if(!categories.includes(draft.Category))categories.push(draft.Category||'Other');for(const c of [...new Set(categories)]){const o=make('option','',c);o.value=c;select.append(o);}select.value=draft.Category||'Other';select.onchange=()=>{draft.Category=select.value;dirty=true;drawEditor();};label.append(make('span','','Category'),select);form.append(label);}
  form.onsubmit=e=>{e.preventDefault();safe(()=>{persist();list();status.textContent='Saved in your Aura tables.';});};panel.append(form,status);
  const foot=make('div','life-tools'),next=button(tab<pages.length-1?'Next ›':'‹ First',()=>{tab=tab<pages.length-1?tab+1:0;drawEditor();}),save=make('button','life-primary','Save entry');save.type='submit';save.setAttribute('form','life-form');foot.append(next,save);panel.append(foot);
  const hint=make('small','life-local',s.key==='family'||occasion?'Birthdays and occasions appear in Timing & signals. Reminders are stored for review, not background alerts.':'Saved in this browser. Available in QuickStart tables and matrix allocation.');panel.append(hint);
  swipe(visual,delta=>{tab=Math.max(0,Math.min(pages.length-1,tab+delta));drawEditor();});
 }
 function connections(focus=null,offset=0){base('Family connections',home);const people=rows().filter(r=>r.recommendation==='relationships');if(!people.length){hero('Start with someone you know','Add a person, then link them to another family member.','people');panel.append(button('+ Add a person',()=>openEditor(null,{Category:s.groups[0].name}),'life-primary'));nav();return;}
  const selected=people.find(r=>rowRef(r)===focus)||people[0],pick=make('select','life-search');pick.setAttribute('aria-label','Person at centre');for(const r of people){const o=make('option','',r.Title);o.value=rowRef(r);pick.append(o);}pick.value=rowRef(selected);pick.onchange=()=>connections(pick.value);panel.append(pick);
  const related=people.filter(r=>r['Connected person']===rowRef(selected)||selected['Connected person']===rowRef(r)),area=make('div','life-network'),centre=button('',()=>openEditor(selected),'life-network-centre');centre.append(icon('people'),make('strong','',selected.Title),make('small','',selected.Relationship||'Family'));area.append(centre);
  related.slice(offset*4,offset*4+4).forEach((r,i)=>{const card=button('',()=>connections(rowRef(r)),`life-network-node node-${i}`);const relationship=r['Connected person']===rowRef(selected)?`${r.Connection||'Connected to'} ${selected.Title}`:`${selected.Title} ${selected.Connection||'connected to'} ${r.Title}`;card.append(make('strong','',r.Title),make('small','',relationship));area.append(card);});panel.append(area);
  panel.append(make('p','life-local',related.length?'Tap a person to centre them. Tap the centre to edit their details.':'No links yet. Edit this person’s Connections tab to link another saved person.'));
  const controls=make('div','life-tools');if(related.length>4){const prev=button('‹',()=>connections(rowRef(selected),offset-1)),next=button('›',()=>connections(rowRef(selected),offset+1));prev.disabled=offset===0;next.disabled=(offset+1)*4>=related.length;controls.append(prev,make('span','',`${offset+1}/${Math.ceil(related.length/4)}`),next);}controls.append(button('Edit person',()=>openEditor(selected),'life-primary'),button('+ Add person',()=>openEditor(null,{Category:s.groups[0].name,'Connected person':rowRef(selected)})));panel.append(controls,status);nav();
 }
 function toolsPage(){mode='tools';base('Bring your data together',()=>category?list():home());hero('Your Aura tables','Import a list, keep a backup or allocate data to your matrix.','book');
  const actions=make('div','life-tool-list');
  const file=make('input');file.type='file';file.accept='.csv,text/csv';file.hidden=true;file.setAttribute('aria-label','Import CSV file');
  file.onchange=async()=>{try{const f=file.files[0];if(!f)return;pending=importLifePreview(await f.text(),s.key,category||'Other');importLife(project,s.key,pending);previewImport();}catch(e){status.textContent=e.message;}};
  actions.append(button('Import CSV list',()=>file.click()),button('Download CSV template',()=>{const columns=[...new Set(['Title','Category',...fieldPages(s,category===s.groups[1]?.name&&s.key==='family').flatMap(p=>p[1].map(f=>f.key))])];download(s.key+'-template.csv','text/csv',csvText([columns]));}),button('Export this collection',()=>{const data=rows(),cols=[...new Set(data.flatMap(r=>Object.keys(r)))].filter(k=>!['tableId','id','recommendation'].includes(k));if(!cols.length){status.textContent='Save an entry first, or download a blank template.';return;}download(s.key+'.csv','text/csv',csvText([cols,...data.map(r=>cols.map(c=>r[c]||''))]));}),button('Back up all Aura data',()=>download('aura-backup.json','application/json',JSON.stringify(readTravelProject(),null,2))),button('Place tables on facets or stacks',()=>go('D203ACAB-C2D1-4433-8EE2-3522C47CC3D0',{step:'allocate'})),button('Open Timing & signals',()=>go('2E5320C1-E2FE-4EE5-B62E-3CB9013D4010')));panel.append(actions,file,make('p','life-local','CSV imports add entries after your review. They never replace your saved entries. Nothing is published or sent to another service.'),status);nav();
 }
 function previewImport(){base('Review your import',toolsPage);hero(`${pending.length} entries to add`,'Existing entries will be kept.','book');const list=make('div','life-import-preview');for(const r of pending.slice(0,5))list.append(make('p','',r.Title+' · '+(r.Category||'Other')));if(pending.length>5)list.append(make('p','',`Plus ${pending.length-5} more entries.`));panel.append(list);const foot=make('div','life-tools');foot.append(button('Cancel',toolsPage),button('Add these entries',()=>safe(()=>{project=writeTravelProject(p=>importLife(p,s.key,pending));pending=null;home();status.textContent='Imported into your Aura tables.';}),'life-primary'));panel.append(foot,status);}
 function swipe(target,fn){let start,suppress=false;target.addEventListener('pointerdown',e=>{start=framePoint(screen,e);suppress=false;});target.addEventListener('pointerup',e=>{if(!start)return;const end=framePoint(screen,e),dx=end.x-start.x,dy=end.y-start.y;start=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)){suppress=true;e.preventDefault();fn(dx<0?1:-1);}});target.addEventListener('click',e=>{if(suppress){e.preventDefault();e.stopImmediatePropagation();suppress=false;}},true);target.addEventListener('pointercancel',()=>start=null);}
 home();return {resize(){},dispose(){}};
}
