import {validateProject} from './core.js?v=0.4.14';
export const make=(tag,cls='',text)=>{const n=document.createElement(tag);n.className=cls;if(text!==undefined)n.textContent=text;return n;};
export const button=(text,fn,cls='')=>{const b=make('button',cls,text);b.type='button';b.onclick=fn;return b;};
export function rows(project,id){const t=project.tables.find(t=>t.id===id);return t?t.rows.map(r=>({id:r.id,...Object.fromEntries(t.columns.map((c,i)=>[c,r.values[i]]))})):[];}
export function saveRow(project,id,name,fields,rowId=crypto.randomUUID(),category='assets'){
 const p=structuredClone(project);let t=p.tables.find(t=>t.id===id);if(!t){t={id,name,category,recommendation:id,chakraTags:[],columns:[],rows:[]};p.tables.push(t);}
 for(const k of Object.keys(fields))if(!t.columns.includes(k)){t.columns.push(k);for(const r of t.rows)r.values.push('');}
 let r=t.rows.find(r=>r.id===rowId);if(!r){r={id:rowId,values:t.columns.map(()=> '')};t.rows.push(r);}
 for(const [k,v]of Object.entries(fields))r.values[t.columns.indexOf(k)]=String(v??'');return validateProject(p);
}
export function removeRow(project,id,rowId){const p=structuredClone(project),t=p.tables.find(t=>t.id===id);if(t)t.rows=t.rows.filter(r=>r.id!==rowId);return validateProject(p);}
export function download(name,value,type='application/json'){const url=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function panelFor(screen,cls=''){for(const n of screen.children)n.hidden=true;const p=make('section','tool-panel '+cls);screen.append(p);return p;}
export function header(panel,title,back){panel.replaceChildren();const h=make('header','tool-header'),b=button('‹',back);b.setAttribute('aria-label','Back');h.append(b,make('h1','',title));panel.append(h);}
export function hero(panel,title,copy,icon='✧'){const h=make('div','tool-hero');if(/\.(png|jpe?g|svg)$/i.test(icon)){const im=make('img');im.src='assets/mockplus/'+icon;im.alt='';h.append(im);}else h.append(make('span','tool-glyph',icon));const c=make('div');c.append(make('strong','',title),make('p','',copy));h.append(c);panel.append(h);}
export function tile(title,copy,icon,fn){const b=button('',fn,'tool-tile');if(/\.(png|jpe?g|svg)$/i.test(icon||'')){const img=make('img');img.src='assets/mockplus/'+icon;img.alt='';b.append(img);}else b.append(make('span','tool-glyph',icon||'✧'));b.append(make('strong','',title),make('small','',copy));return b;}
export function grid(panel,items,size=6){let page=0;const wrap=make('div','tool-grid'),nav=make('nav','tool-pager');panel.append(wrap,nav);function draw(){wrap.replaceChildren();nav.replaceChildren();items.slice(page*size,(page+1)*size).forEach(item=>wrap.append(item()));wrap.dataset.count=String(wrap.children.length);if(items.length>size){const prev=button('‹',()=>{page--;draw();}),next=button('›',()=>{page++;draw();});prev.setAttribute('aria-label','Previous group');next.setAttribute('aria-label','Next group');prev.disabled=page===0;next.disabled=(page+1)*size>=items.length;nav.append(prev,make('span','',`${page+1} / ${Math.ceil(items.length/size)}`),next);}}draw();}
// Small labelled steps keep every field usable in the original fixed phone frame.
export function editor(panel,{title,back,pages,values={},save,remove,copy=''}){
 let step=0;const draft={...values};function draw(){header(panel,title,back);if(copy)panel.append(make('p','tool-help',copy));const tabs=make('nav','tool-tabs');pages.forEach(([label],i)=>{const b=button(label,()=>{step=i;draw();});b.setAttribute('aria-current',String(step===i));tabs.append(b);});panel.append(tabs);const form=make('form','tool-form'),status=make('p','tool-status');status.setAttribute('role','status');
 for(const spec of pages[step][1]){const [key,label,type='text',options]=spec,wrap=make('label','',label);let input;if(type==='select'){input=make('select');for(const o of options){const [v,t]=Array.isArray(o)?o:[o,o],option=make('option','',t);option.value=v;input.append(option);}}else input=make(type==='textarea'?'textarea':'input');if(!['select','textarea'].includes(type))input.type=type;if(type==='number')input.step='any';input.value=draft[key]??(type==='select'?(Array.isArray(options[0])?options[0][0]:options[0]):'');if(type==='select')draft[key]=input.value;input.setAttribute('aria-label',label);input.oninput=()=>draft[key]=input.value;wrap.append(input);form.append(wrap);}
 const foot=make('footer','tool-footer');if(remove)foot.append(button('Remove',()=>{if(confirm('Remove this saved item?')){remove();back();}}));if(step<pages.length-1)foot.append(button('Next',()=>{step++;draw();}));const s=make('button','tool-primary','Save');s.type='submit';foot.append(s);form.append(status,foot);form.onsubmit=e=>{e.preventDefault();try{save(draft);status.textContent='Saved in this browser.';}catch(error){status.textContent=error.message;}};panel.append(form);}
 draw();return draft;
}
