import {make,button,rows,saveRow,removeRow,panelFor,header,hero,tile,grid,editor} from './local-tools.js?v=0.4.9';
import {readTravelProject,writeTravelProject} from './travel-data.js?v=0.4.9';
import {pageIcon} from './page-icons.js?v=0.4.9';
export const PALACE='F9CE754E-27BE-49C3-AD43-F39BCEC0B3E8',SAMPLE_PALACE='B80C2D52-3C95-4E1F-94C5-9D214348D2E0';
export const PALACE_PAGES=new Set([PALACE,SAMPLE_PALACE,'DFB43FEB-2BDF-422E-BCBF-0F4021E82F32','D34C877A-6E49-43C4-88E5-D033C8B7E02E','3B9E03CA-EF05-4B0B-B004-E95AFCA1C713','C490FE96-B734-4273-9256-DD9088241222']);
export function saveRoom(project,fields,id=crypto.randomUUID()){
 if(!fields.Title?.trim())throw Error('Give this room or space a name.');if(!PALACE_PAGES.has(fields.Section)||fields.Section===PALACE)throw Error('Choose a palace section.');
 if(!Number.isFinite(+fields.Width)||!Number.isFinite(+fields.Length)||+fields.Width<=0||+fields.Length<=0)throw Error('Enter positive width and length measurements in metres.');
 return saveRow(project,'aura-palace-rooms','Mind palace rooms',fields,id,'place');
}
export function savePin(project,fields,id=crypto.randomUUID()){
 if(!rows(project,'aura-palace-rooms').some(r=>r.id===fields.Room))throw Error('This room is no longer available.');if(!fields.Title?.trim())throw Error('Give the pin a name.');
 for(const k of ['X','Y'])if(!Number.isFinite(+fields[k])||+fields[k]<0||+fields[k]>1)throw Error('Place the pin inside the room.');
 if(fields.Table&&!project.tables.some(t=>t.id===fields.Table))throw Error('Choose an available table.');
 if(fields.Facet&&!/^(Red|Orange|Yellow|Green|Blue|Indigo|Violet) [IO](?:[1-9]|[1-9]\d|1\d\d|2[0-7]\d|28[0-8])$/.test(fields.Facet))throw Error('Use an address such as Red O1, up to 288.');
 if(fields.Asset&&!/^https?:\/\//i.test(fields.Asset))throw Error('Use a full https:// or http:// asset link.');
 return saveRow(project,'aura-palace-pins','Mind palace information pins',fields,id,'assets');
}
export function removeRoom(project,id){let p=removeRow(project,'aura-palace-rooms',id);for(const pin of rows(p,'aura-palace-pins').filter(r=>r.Room===id))p=removeRow(p,'aura-palace-pins',pin.id);return p;}
export function samplePalace(project){if(rows(project,'aura-palace-rooms').some(r=>r.Section===SAMPLE_PALACE))return project;let p=project;for(const [i,title,meaning]of [[1,'Entrance','Recall your intention for today'],[2,'Study','Keep a useful idea or learning here'],[3,'Garden','Recall something you are grateful for']]){const id='sample-palace-room-'+i;p=saveRoom(p,{Title:title,Section:SAMPLE_PALACE,Width:'4',Length:'5',Notes:'Sample room. Rename or replace with your own space.'},id);p=savePin(p,{Title:title+' memory',Room:id,X:'.5',Y:'.5',Meaning:meaning},'sample-palace-pin-'+i);}return p;}
const ns='http://www.w3.org/2000/svg';
const svgNode=(tag,attrs={})=>{const n=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;};
export function mountPalace({page,screen,pages,go}){
 const panel=panelFor(screen,'palace-panel');let placing=false;
 const getRooms=()=>rows(readTravelProject(),'aura-palace-rooms').filter(r=>r.Section===page.id),getPins=room=>rows(readTravelProject(),'aura-palace-pins').filter(p=>p.Room===room.id);
 function home(){header(panel,page.id===PALACE?'Mind Palaces':page.name,()=>go(page.id===PALACE?'command:back':PALACE));
  hero(panel,'Give information a place',page.id===PALACE?'Rooms, objects and familiar places become anchors for your memories and ideas.':'Tap a room to place or revisit information. Plans are 2D and saved locally.',pageIcon(page.id)||'⌂');
  if(page.id===PALACE){grid(panel,[...pages.values()].filter(p=>p.parent===PALACE).map(p=>()=>tile(p.name,`${rows(readTravelProject(),'aura-palace-rooms').filter(r=>r.Section===p.id).length} spaces`,pageIcon(p.id),()=>go(p.id))),6);return;}
  const rooms=getRooms();grid(panel,[()=>tile('New room or space','Name it and set its dimensions','+',()=>editRoom()),...rooms.map(r=>()=>tile(r.Title,`${r.Width} × ${r.Length} m · ${getPins(r).length} pins`,'⌂',()=>room(r)))],6);
  if(page.id===SAMPLE_PALACE&&!rooms.length)panel.append(button('Create the sample palace',()=>{writeTravelProject(samplePalace);home();},'tool-primary'));
  if(rooms.length)panel.append(button('Walk through this palace',()=>walk(0),'tool-primary'));
 }
 function editRoom(existing){const id=existing?.id||crypto.randomUUID();editor(panel,{title:existing?.Title||'New space',back:home,values:existing||{},copy:'Use real measurements when known, or enter a chosen layout size.',pages:[['Space',[['Title','Room, building or outdoor space'],['Width','Width (metres)','number'],['Length','Length (metres)','number'],['Notes','Landmarks or memory theme','textarea']]]],save:v=>writeTravelProject(p=>saveRoom(p,{...v,Section:page.id},id)),remove:existing?()=>writeTravelProject(p=>removeRoom(p,id)):null});}
 function room(r){placing=false;header(panel,r.Title,home);const controls=make('div','tool-tabs');controls.append(button('Room details',()=>editRoom(r)),button('Place a pin',()=>{placing=true;hint.textContent='Tap inside the room to place your new pin.';}),button('Recall',()=>walk(0,r)));panel.append(controls);
  const hint=make('p','tool-help','Tap a pin to read or edit. Drag a pin to move it.');panel.append(hint);const canvas=make('div','palace-canvas');panel.append(canvas);const svg=svgNode('svg',{viewBox:'0 0 320 310',role:'img','aria-label':`${r.Title}, ${r.Width} by ${r.Length} metres`});canvas.append(svg);
  const scale=Math.min(260/+r.Width,240/+r.Length),w=+r.Width*scale,h=+r.Length*scale,x=(320-w)/2,y=(270-h)/2+10;
  svg.append(svgNode('rect',{x,y,width:w,height:h,rx:2,fill:'#eee8f8',stroke:'#776491','stroke-width':3}));
  const lineStep=Math.max(1,Math.ceil(Math.max(+r.Width,+r.Length)/20));for(let m=lineStep;m<+r.Width;m+=lineStep)svg.append(svgNode('path',{d:`M${x+m*scale} ${y}v${h}`,stroke:'#d5cbe4'}));for(let m=lineStep;m<+r.Length;m+=lineStep)svg.append(svgNode('path',{d:`M${x} ${y+m*scale}h${w}`,stroke:'#d5cbe4'}));
  const label=svgNode('text',{x:160,y:296,'text-anchor':'middle',fill:'#584765','font-size':12});label.textContent=`${r.Width} × ${r.Length} m · grid ${lineStep} m`;svg.append(label);
  function point(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());return {X:Math.max(0,Math.min(1,(p.x-x)/w)),Y:Math.max(0,Math.min(1,(p.y-y)/h))};}
  svg.onclick=e=>{if(placing){const pt=point(e);editPin(r,{Room:r.id,...pt});}};
  getPins(r).forEach((pin,i)=>{const g=svgNode('g',{tabindex:0,role:'button','aria-label':pin.Title,transform:`translate(${x+pin.X*w} ${y+pin.Y*h})`}),dot=svgNode('circle',{r:13,fill:'#7954aa',stroke:'white','stroke-width':2}),n=svgNode('text',{'text-anchor':'middle',y:4,fill:'white','font-size':11});n.textContent=i+1;g.append(dot,n);svg.append(g);let start=null,moved=false,pt=null;g.onpointerdown=e=>{e.stopPropagation();start={x:e.clientX,y:e.clientY};moved=false;g.setPointerCapture(e.pointerId);};g.onpointermove=e=>{if(!start)return;pt=point(e);if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>5)moved=true;if(moved)g.setAttribute('transform',`translate(${x+pt.X*w} ${y+pt.Y*h})`);};g.onpointerup=e=>{if(!start)return;start=null;if(moved){try{writeTravelProject(p=>savePin(p,{...pin,...pt},pin.id));hint.textContent='Pin position saved.';}catch(error){hint.textContent=error.message;}}else editPin(r,pin);e.stopPropagation();};g.onpointercancel=()=>{start=null;room(r);};g.onclick=e=>e.stopPropagation();g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();editPin(r,pin);}};});
  const labels=make('div','palace-key');getPins(r).forEach((p,i)=>labels.append(button(`${i+1}. ${p.Title}`,()=>editPin(r,p))));panel.append(labels);if(!getPins(r).length)panel.append(make('p','tool-help','Place a pin at a memorable landmark, then attach an idea, data or instructions.'));
 }
 function editPin(r,pin){const id=pin.id||crypto.randomUUID(),p=readTravelProject();editor(panel,{title:pin.Title||'Information pin',back:()=>room(r),values:pin,pages:[['Memory',[['Title','Pin title'],['Meaning','What belongs here?','textarea'],['Asset','Image, document or asset URL','url']]],['Data',[['Table','Link an Aura table','select',[['','No table selected'],...p.tables.map(t=>[t.id,t.name])]],['Data','Information to remember','textarea'],['Facet','Facet address (for example Red O1)']]],['Instructions',[['Instructions','Instructions for an agent','textarea'],['Cue','Recall cue or question','textarea']]]],save:v=>writeTravelProject(p=>savePin(p,{...v,Room:r.id},id)),remove:pin.id?()=>writeTravelProject(p=>removeRow(p,'aura-palace-pins',id)):null});}
 function walk(index,onlyRoom=null,reveal=false){const rooms=onlyRoom?[onlyRoom]:getRooms(),items=rooms.flatMap(r=>getPins(r).map(pin=>({r,pin})));header(panel,'Palace walkthrough',()=>onlyRoom?room(onlyRoom):home());if(!items.length){hero(panel,'Place your first memory','Add a pin to a room before starting a walkthrough.','⌂');return;}index=(index+items.length)%items.length;const {r,pin}=items[index];hero(panel,r.Title,`${index+1} of ${items.length} · ${pin.Title}`,'⌂');const card=make('div','palace-recall');card.append(make('h2','',pin.Cue||'What did you place here?'));if(reveal){card.append(make('p','',pin.Meaning||pin.Data||'No memory text entered yet.'));if(pin.Data&&pin.Meaning&&pin.Data!==pin.Meaning)card.append(make('p','',pin.Data));if(pin.Instructions)card.append(make('p','',pin.Instructions));if(pin.Asset){const a=make('a','','Open attached asset ↗');a.href=pin.Asset;a.target='_blank';a.rel='noopener';card.append(a);}if(pin.Table){const t=readTravelProject().tables.find(t=>t.id===pin.Table);card.append(make('p','',t?`${t.name} · ${t.rows.length} rows`:'Linked table is unavailable.'));}if(pin.Facet)card.append(make('p','',pin.Facet));}else card.append(button('Reveal memory',()=>walk(index,onlyRoom,true)));panel.append(card);const f=make('footer','tool-footer');f.append(button('‹ Previous',()=>walk(index-1,onlyRoom)),button('Edit pin',()=>editPin(r,pin)),button('Next ›',()=>walk(index+1,onlyRoom)));panel.append(f);}
 home();return {resize(){},dispose(){}};
}
