import {make,button,rows,saveRow,removeRow,download,panelFor,header,hero,tile,grid,editor} from './local-tools.js?v=0.4.13';
import {readTravelProject,writeTravelProject} from './travel-data.js?v=0.4.13';
import {pageIcon} from './page-icons.js?v=0.4.13';
export const PREFERENCES='3F0068AA-FE6A-4C6F-B9ED-F7B62B407790';
const ADS='BE2F4956-CAE7-4CF3-9088-A62B7EA190C8',MEMORY='2C355653-BAA4-4BC3-A9B8-7567A12F3962',DEVICES='EC64984C-1A60-42E1-BEFF-E849B2778AB9',ALGORITHMS='7059638E-B7C3-4EC9-85CE-21FDD8A5E87A',DRONES='4970BEC1-052E-432E-B7F0-45E42C762623';
export function underPage(page,pages,root){const seen=new Set();while(page&&!seen.has(page.id)){if(page.id===root)return true;seen.add(page.id);page=pages.get(page.parent);}return false;}
const descriptions={'Advertising Options':'Choose what you welcome, support or share',Memory:'Your saved data, tables and backups','Network Devices':'Keep track of devices and their roles',Algorithms:'Choose inputs, rules and intended outputs',Sponsorships:'Causes, support and reciprocal commitments','Incoming Advertising':'Topics, frequency and offers you welcome',Crowdfunding:'Projects, contributions and campaign links','Public Wish Lists':'Choose which wishes to include in a shareable file'};
const algorithmHints={
 'Gaze Tracking':['Look position or gaze samples','When a gaze is held on a target','Highlight the selected target'],
 'Face Recognition':['Consented face references','When a known reference matches','Ask before linking to a person'],
 'Object Detection':['Labelled objects and images','When an object appears','Add an observation to a facet'],
 'Hand Tracking':['Hand poses and gestures','When a gesture is recognised','Trigger the chosen interface action'],
 'Navigation Pathfinder':['Places, paths and access needs','When a destination is chosen','Compare available paths'],
 'Multi-Stop Journey Planner':['Places, dates and constraints','When a trip changes','Suggest an ordered itinerary'],
 'Home Automation':['Devices and timing signals','When a chosen signal occurs','Request the specified device action'],
 'Personal Assistant':['Your selected tables and goals','When you request help','Prepare a useful next step']};
export function saveAlgorithm(project,id,fields){if(fields.Dataset&&!project.tables.some(t=>t.id===fields.Dataset))throw Error('Choose an available dataset.');if(fields.Device&&!rows(project,'aura-devices').some(r=>r.id===fields.Device))throw Error('Choose a saved device.');if(!fields.Title?.trim())throw Error('Give the configuration a name.');return saveRow(project,'aura-algorithms','Algorithm configurations',{...fields,Status:'Configuration only'},id,'intent');}
export function mountPreferences({page,screen,pages,go}){
 const panel=panelFor(screen,'preferences-panel'),back=()=>go(page.id===PREFERENCES?'command:back':page.parent||PREFERENCES),icon=pageIcon(page.id)||'⚙';
 const start=()=>{header(panel,page.name,back);};
 function home(){start();
  if(page.id===MEMORY){memory();return;}if(page.id===DEVICES||page.id===DRONES){devices();return;}
  if(page.parent===ALGORITHMS){algorithm();return;}
  if(page.parent===ADS){advertising();return;}
  hero(panel,page.id===PREFERENCES?'Make Aura work your way':page.name,page.id===PREFERENCES?'Your choices, data, devices and tools.':descriptions[page.name]||'Choose a tool and prepare its data and behaviour.',icon);
  const order=page.controls.slice().sort((a,b)=>+a.y-+b.y||+a.x-+b.x).flatMap(c=>c.links.map(l=>l.target)),children=[...pages.values()].filter(p=>p.parent===page.id).sort((a,b)=>order.indexOf(a.id)-order.indexOf(b.id));grid(panel,children.map(p=>()=>tile(p.name,descriptions[p.name]||(rows(readTravelProject(),'aura-algorithms').some(r=>r.id===p.id)?'Configuration saved':'Choose data, rules and outputs'),pageIcon(p.id),()=>go(p.id))),page.id===ALGORITHMS?8:6);
  if(page.id===PREFERENCES){const foot=make('footer','tool-footer');foot.append(button('Backup Aura',()=>download('aura-backup.json',readTravelProject())));panel.append(foot);}
 }
 function memory(){const p=readTravelProject(),bytes=new TextEncoder().encode(JSON.stringify(p)).length,total=p.tables.reduce((n,t)=>n+t.rows.length,0);hero(panel,'Your saved Aura',`${p.tables.length} tables · ${total} rows · ${(bytes/1024).toFixed(1)} KB in the project backup`,icon);
  const stats=make('div','memory-stats');for(const [n,label]of [[p.records.length,'Facet records'],[p.stacks.length,'Stacks'],[p.programs.length,'Programs']]){const box=make('div');box.append(make('strong','',n),make('span','',label));stats.append(box);}panel.append(stats);
  grid(panel,p.tables.map(t=>()=>tile(t.name,`${t.rows.length} rows · ${t.columns.length} fields`,'▤',()=>table(t))),4);
  if(!p.tables.length)panel.append(make('p','tool-help','QuickStart and the other Aura tools create tables here as you save.'));
  const f=make('footer','tool-footer');f.append(button('Download backup',()=>download('aura-backup.json',readTravelProject())),button('Import & allocate',()=>{location.href='matrix.html?from='+page.id;}));panel.append(f,make('p','tool-help','Project size is measured locally. Device capacity and cloud storage are not connected.'));
 }
 function table(t){header(panel,t.name,home);hero(panel,'Table contents',`${t.rows.length} saved rows. Included in your Aura backup.`,'▤');grid(panel,t.rows.map(r=>()=>tile(r.values[0]||'Untitled',`${t.columns.length} fields`,'▤',()=>{header(panel,r.values[0]||t.name,()=>table(t));const fields=t.columns.map((c,i)=>[c,r.values[i]]);grid(panel,fields.map(([k,v])=>()=>tile(k,v||'Not entered','',()=>{header(panel,k,()=>table(t));const text=make('textarea','tool-read');text.readOnly=true;text.value=v;panel.append(text);})),6);})),6);panel.append(button('Export this table',()=>download(t.name+'.json',t),'tool-primary'));}
 function devices(){hero(panel,page.id===DRONES?'Services & drones':'Your device network','Record equipment and its purpose. Entries are manual, not live connections.',icon);const list=rows(readTravelProject(),'aura-devices').filter(r=>(r.Kind==='Drone / service')===(page.id===DRONES));grid(panel,[()=>tile('Add '+(page.id===DRONES?'service':'device'),'Name it and choose its role','+',()=>device()),...list.map(r=>()=>tile(r.Title,r.Role||r.Kind,'▣',()=>device(r)))],6);if(page.id===DEVICES)panel.append(button('Services & drones',()=>go(DRONES),'tool-primary'));}
 function device(existing){const id=existing?.id||crypto.randomUUID();editor(panel,{title:existing?.Title||'Add device',back:home,values:existing||{Kind:page.id===DRONES?'Drone / service':'Computer'},copy:'Inventory only. No device is contacted or paired.',pages:[['Device',[
 ['Title','Device or service name'],['Kind','Type','select',['Computer','Phone','Tablet','Sensor','Storage','Home device','Drone / service','Other']],['Role','What will it do?'],['Location','Where is it?']]],['Details',[
 ['Address','Reference or service URL'],['Capabilities','Inputs and capabilities','textarea'],['Notes','Connection notes','textarea']]]],save:v=>{if(!v.Title?.trim())throw Error('Enter a device name.');writeTravelProject(p=>saveRow(p,'aura-devices','Devices and services',v,id));},remove:existing?()=>writeTravelProject(p=>removeRow(p,'aura-devices',id)):null});}
 function algorithm(){const p=readTravelProject(),saved=rows(p,'aura-algorithms').find(r=>r.id===page.id)||{Title:page.name},hints=algorithmHints[page.name]||['Selected data and observations','When the chosen conditions are met','A suggestion or action for you to review'];
  hero(panel,page.name,'Prepare the input → rule → output. This saves a specification; it does not install or run an algorithm.',icon);const flow=make('div','algorithm-flow');['Data','Rule','Review','Output'].forEach((v,i)=>flow.append(make('span','',`${i+1} ${v}`)));panel.append(flow);
  grid(panel,[()=>tile('Inputs',hints[0],'▤',()=>configure(0)),()=>tile('When & how',hints[1],'◷',()=>configure(1)),()=>tile('Output',hints[2],'↗',()=>configure(2)),()=>tile('Export specification','For an agent or developer to read','↓',()=>download('aura-'+page.name+'.json',{tool:page.name,configuration:saved,status:'Configuration only',dataset:p.tables.find(t=>t.id===saved.Dataset)||null}))],4);
  panel.append(make('p','tool-help',saved.Rule?'Saved rule: '+saved.Rule:'No rule entered yet. Choose a card to begin.'));
  function configure(step){const configs=[['Inputs',[['Title','Configuration name'],['Dataset','Aura dataset','select',[['','Choose a table'],...p.tables.map(t=>[t.id,t.name])]],['Device','Device','select',[['','No device selected'],...rows(p,'aura-devices').map(r=>[r.id,r.Title])]],['Purpose','Purpose','textarea']]],['Rule',[['Trigger','Trigger or timing signal'],['Rule','Conditions and instructions','textarea'],['Constraints','Limits and exceptions','textarea']]],['Output',[['Output','Desired output or action','textarea'],['Review','Review before action','select',['Ask me first','Draft only']],['Destination','Destination facet, stack or tool']]]];editor(panel,{title:page.name,back:home,values:saved,pages:[configs[step],...configs.filter((_,i)=>i!==step)],save:v=>writeTravelProject(p=>saveAlgorithm(p,page.id,v))});}
 }
 function advertising(){const existing=rows(readTravelProject(),'aura-preferences').find(r=>r.id===page.id)||{},wish=page.name==='Public Wish Lists';
  hero(panel,page.name,descriptions[page.name]||'Choose what matters to you.',icon);
  if(wish){panel.append(make('p','tool-help','Choose individual wishes to export. Nothing is published automatically.'));const wishes=readTravelProject().tables.flatMap(t=>t.rows.map(r=>({table:t,row:r,values:Object.fromEntries(t.columns.map((c,i)=>[c,r.values[i]]))}))).filter(r=>['wishes','bucket'].includes(r.values.Collection)),selected=new Set();const list=make('div','tool-choice-list');for(const w of wishes){const label=make('label'),check=make('input');check.type='checkbox';check.onchange=()=>check.checked?selected.add(w):selected.delete(w);label.append(check,make('span','',w.values.Title||'Untitled wish'));list.append(label);}panel.append(list);if(!wishes.length)panel.append(button('Add wishes',()=>go('4EE0FBBC-65BF-49B1-9D77-7022C1FD6E1D')));const exportButton=button('Export selected titles',()=>download('my-selected-wishes.json',[...selected].map(w=>({title:w.values.Title,category:w.values.Category||''}))));panel.append(exportButton);return;}
  const ad=page.name==='Incoming Advertising';grid(panel,[()=>tile(ad?'Offers & topics':'Interests','Choose the topics and causes you welcome','♡',()=>form()),()=>tile(ad?'Frequency & boundaries':'Plans & commitments','Set your own limits and next steps','◷',()=>form())],2);
  panel.append(make('p','tool-help',existing.Topics?'Saved interests: '+existing.Topics:'Nothing selected yet. Your choices stay in this browser.'));
  function form(){editor(panel,{title:page.name,back:home,values:existing,pages:[['Interests',[['Topics',ad?'Topics I welcome':'Causes or projects of interest','textarea'],['Avoid','Topics or approaches to avoid','textarea'],['Reference','Campaign or reference URL','url']]],['Preferences',[['Frequency','Preferred frequency','select',['','Off','Only when I ask','Weekly summary','Monthly summary']],['Budget','Budget or contribution limit'],['Commitment','What I would like to contribute','textarea'],['Next step','Next step']]]],copy:'Planning preferences only. No advertising feed, payment or campaign account is connected.',save:v=>writeTravelProject(p=>saveRow(p,'aura-preferences','System preferences',{Title:page.name,...v},page.id))});}
 }
 home();return {resize(){},dispose(){}};
}
