import {mountDating} from './dating-ui.js?v=0.4.10';
import {make,button,rows,saveRow,removeRow,download,panelFor,header,hero,tile,grid,editor} from './local-tools.js?v=0.4.10';
import {readTravelProject,writeTravelProject,dateValid} from './travel-data.js?v=0.4.10';
import {parseCSV,validateProject} from './core.js?v=0.4.10';
import {saveTiming} from './timing-data.js?v=0.4.10';
import {LIFE_SECTIONS,SOCIAL_HOME} from './life-data.js?v=0.4.10';
import {pageIcon} from './page-icons.js?v=0.4.10';
export const SOCIAL_ACCESS='1D740128-8621-43EE-8D85-E81F0241A569',SOCIAL_IMPORT='7E5774BE-BCC6-4684-8A88-0F8D2A26B1F0',SOCIAL_ANALYSE='C49B4FEE-90BF-499A-AE2C-CDA004D27C57',DATING='1FA4EBEC-3D1A-482A-B3B2-35A1172BECB6',FRIENDS='76172966-3F90-4DB8-A914-4E63AE19A501';
export const FAMILY_BELONGING='AE87688C-93C9-4AB1-A72D-A447ED56C5E0';
const DATING_IMPORT='B8FE6EA7-4EC0-4425-905D-E4650DD935E8';
export function addSocialPages(source){const dating=source.pages.find(p=>p.id===DATING);if(dating){dating.parent=FAMILY_BELONGING;dating.name='Dating';}if(!source.pages.some(p=>p.id===FRIENDS))source.pages.push({id:FRIENDS,name:'Friendships',parent:FAMILY_BELONGING,width:360,height:640,orientation:'MoPortrait',background:'4294967295',controls:[]});return source;}
export const isSocialPage=p=>[SOCIAL_HOME,SOCIAL_ACCESS,SOCIAL_IMPORT,SOCIAL_ANALYSE,DATING,FRIENDS,DATING_IMPORT].includes(p.id)||[SOCIAL_ACCESS,SOCIAL_IMPORT].includes(p.parent);
export function importSocial(project,name,text){const csv=parseCSV(text);if(!csv.headers.length||!csv.rows.length)throw Error('Include a header row and at least one data row.');const p=structuredClone(project);p.tables.push({id:crypto.randomUUID(),name,category:'people',recommendation:'social-import',chakraTags:[3,4],columns:csv.headers,rows:csv.rows.map(values=>({id:crypto.randomUUID(),values}))});return validateProject(p);}
export function socialSummary(project){return project.tables.filter(t=>t.recommendation==='social-import').map(t=>({id:t.id,name:t.name,rows:t.rows.length,columns:t.columns.length,filled:t.rows.reduce((sum,r)=>sum+r.values.filter(v=>v.trim()).length,0),cells:t.rows.length*t.columns.length}));}
export function saveConnection(project,kind,fields,id){if(!['dating','friends'].includes(kind))throw Error('Unknown connection type.');if(!fields.Title?.trim())throw Error('Enter a name or group.');if(!dateValid(fields['Last catch-up']||'')||!dateValid(fields['Next catch-up']||''))throw Error('Enter a valid catch-up date.');return saveRow(project,'aura-'+kind,kind==='dating'?'Dating and relationships':'Friendships and circles',fields,id,'people');}
export function mountSocial({page,screen,pages,go}){
 const panel=panelFor(screen,'social-panel'),kind=[DATING,DATING_IMPORT].includes(page.id)?'dating':'friends',back=()=>go(page.id===SOCIAL_HOME?'command:back':[DATING,DATING_IMPORT,FRIENDS].includes(page.id)?FAMILY_BELONGING:SOCIAL_HOME);
 function home(){header(panel,page.id===SOCIAL_HOME?'Social Web':page.id===SOCIAL_ACCESS?'Social media':page.id===SOCIAL_IMPORT?'Import social data':page.id===SOCIAL_ANALYSE?'Explore your social data':page.name,back);
  if([DATING,DATING_IMPORT,FRIENDS].includes(page.id)){mountDating({panel,back,people:connectionList,catchup,kind});return;}
  if(page.id===SOCIAL_HOME){hero(panel,'Your people & possibilities','Keep connections, wishes, memories and plans together.','♡');const actions=make('div','tool-tabs');for(const [label,id]of [['Profiles',SOCIAL_ACCESS],['Import',SOCIAL_IMPORT],['Explore',SOCIAL_ANALYSE]])actions.append(button(label,()=>go(id)));panel.append(actions);
   const items=[...LIFE_SECTIONS.map(s=>[s.title,s.key==='family'?'Family, friendships and dating':'Ideas and saved entries',s.id]),['Travel plans','Places visited and places to go','DAFCEEE9-7303-415D-975B-AB7176A59010']];grid(panel,items.map(([title,copy,id])=>()=>tile(title,copy,pageIcon(id)||'♡',()=>go(id))),8);return;}
  if(page.id===SOCIAL_ANALYSE){analyse();return;}
  if(page.id===SOCIAL_IMPORT||page.parent===SOCIAL_IMPORT){importView();return;}
  if(page.id===SOCIAL_ACCESS){hero(panel,'Your profiles, in one place','Keep profile links and interests together. No platform account is connected.',pageIcon(page.id)||'◎');const platforms=[...pages.values()].filter(p=>p.parent===SOCIAL_ACCESS&&p.id!==DATING);grid(panel,platforms.map(p=>()=>tile(p.name,rows(readTravelProject(),'aura-social-profiles').some(r=>r.id===p.id)?'Profile saved':'Add a profile or plan',pageIcon(p.id)||'◎',()=>go(p.id))),8);return;}
  if(page.id==='17ACD7EE-5D4E-4DC8-812F-9B0CE2916511'){editor(panel,{title:'Plan a service connection',back:()=>go(SOCIAL_ACCESS),values:rows(readTravelProject(),'aura-preferences').find(r=>r.id===page.id)||{},copy:'Keep a request ready for development. This does not submit it or connect an account.',pages:[['Service',[['Title','Service or platform name'],['URL','Documentation or service URL','url'],['Data','Data you would like to bring in','textarea'],['Purpose','What would it help you do?','textarea']]]],save:v=>{if(!v.Title?.trim())throw Error('Name the service.');writeTravelProject(p=>saveRow(p,'aura-preferences','System preferences',v,page.id));}});return;}
  profile();
 }
 function profile(){const existing=rows(readTravelProject(),'aura-social-profiles').find(r=>r.id===page.id)||{};hero(panel,page.name,existing.Title||'Bring the useful parts of this service into Aura.',pageIcon(page.id)||'◎');grid(panel,[()=>tile('Profile & purpose',existing.Title||'Add a profile and what matters to you','◎',configure),()=>tile('Import an export','Review a CSV before adding it to Aura','↓',()=>go(SOCIAL_IMPORT)),()=>tile('Explore your data','See fields, counts and completeness','▤',()=>go(SOCIAL_ANALYSE))],4);if(existing.URL&&/^https?:\/\//i.test(existing.URL)){const link=make('a','tool-external','Open saved profile ↗');link.href=existing.URL;link.target='_blank';link.rel='noopener';panel.append(link);}function configure(){editor(panel,{title:page.name,back:home,values:existing,copy:'Save links and intentions here. Aura does not request passwords or log into this service.',pages:[['Profile',[['Title','Display name or account'],['URL','Public profile or service URL','url'],['Purpose','What do you use it for?','textarea']]],['Interests',[['Topics','Topics, groups and interests','textarea'],['Keep','What would you like to bring into Aura?','textarea'],['Review date','Next review date','date']]]],save:v=>{if(!v.Title?.trim())throw Error('Enter a display name or account.');if(v.URL&&!/^https?:\/\//i.test(v.URL))throw Error('Use a full http:// or https:// URL.');writeTravelProject(p=>saveRow(p,'aura-social-profiles','Social media profiles',{Platform:page.name,...v},page.id,'people'));}});}}
 function connectionList(){header(panel,kind==='dating'?'People & connections':'Friends & circles',home);const list=rows(readTravelProject(),'aura-'+kind);hero(panel,'Your connections','People you know or would like to get to know.',kind==='dating'?'♡':'♧');grid(panel,[()=>tile(kind==='dating'?'Add a person':'Add a person or group','Keep useful details and next steps','+',()=>person()),...list.map(r=>()=>tile(r.Title,r['Next catch-up']?'Next: '+r['Next catch-up']:r.Context||r.Interests||'Open connection',kind==='dating'?'♡':'♧',()=>person(r)))],6);}
 function person(existing){const id=existing?.id||crypto.randomUUID();editor(panel,{title:existing?.Title||'New connection',back:home,values:existing||{},pages:[['Person',[['Title','Name or group'],['Context','How we know each other'],['Interests','Shared interests','textarea'],['Contact','Contact or profile link']]],['Connection',[['Stage','Connection stage','select',['','Would like to meet','Getting to know each other','Staying in touch','Close connection','On pause']],['Notes','Things to remember','textarea'],['Boundaries','Communication preferences','textarea']]],['Plans',[['Last catch-up','Last catch-up','date'],['Next catch-up','Next catch-up','date'],['Ideas','Ideas for time together','textarea'],['Rhythm','Preferred contact rhythm']]]],save:v=>writeTravelProject(p=>saveConnection(p,kind,v,id)),remove:existing?()=>writeTravelProject(p=>removeRow(p,'aura-'+kind,id)):null});}
 function catchup(){let saved=null;editor(panel,{title:'Plan a catch-up',back:home,copy:'This adds a calendar entry to Timing & signals. It does not send an invitation.',pages:[['Plan',[['Title','Catch-up or occasion'],['Date','Date','date'],['Time','Time','time'],['People','Who is involved?']]],['Details',[['Place','Place or meeting link'],['Meaning','What would you like to do?','textarea'],['Reminder minutes','Reminder lead time in minutes','number']]]],save:v=>{const fields={...v};if(!fields['Reminder minutes'])delete fields['Reminder minutes'];const result=writeTravelProject(p=>saveTiming(p,'schedules',fields,saved));if(!saved){const t=result.tables.find(t=>t.id==='timing-schedules');saved={tableId:t.id,id:t.rows.at(-1).id};}}});}
 function importView(){hero(panel,page.id===SOCIAL_IMPORT?'Bring your data into Aura':page.name+' data','Import a CSV export and review it before saving. All columns are retained.','↓');const file=make('input');file.type='file';file.accept='.csv,text/csv';file.setAttribute('aria-label','Choose a social data CSV');const status=make('p','tool-status');status.setAttribute('role','status');panel.append(file,status,button('Download a starter CSV',()=>download('social-data-template.csv','Name,Platform,Profile URL,Interests,Notes\r\n','text/csv')),make('p','tool-help','Use a CSV from your own export, or fill in the starter. ZIP archives and direct account sync are not supported yet.'));
  file.onchange=async()=>{try{const f=file.files[0];if(!f)return;const text=await f.text(),parsed=parseCSV(text);importSocial(readTravelProject(),f.name,text);preview(f.name,text,parsed);}catch(e){status.textContent=e.message;}};
 }
 function preview(name,text,csv){header(panel,'Review import',home);hero(panel,name,`${csv.rows.length} rows · ${csv.headers.length} columns. Nothing saved yet.`,'▤');grid(panel,csv.headers.map((h,i)=>()=>tile(h,csv.rows.slice(0,3).map(r=>r[i]||'Empty').join(' · '),'▤',()=>{})),6);const status=make('p','tool-status'),save=button('Save this dataset',()=>{try{writeTravelProject(p=>importSocial(p,name.replace(/\.csv$/i,''),text));save.disabled=true;panel.querySelector('.tool-hero p').textContent=`${csv.rows.length} rows saved with all ${csv.headers.length} columns.`;status.textContent='Saved. Explore this dataset or allocate it in the matrix.';}catch(e){status.textContent=e.message;}},'tool-primary');panel.append(save,status,button('Explore datasets',()=>go(SOCIAL_ANALYSE)));}
 function analyse(){const summary=socialSummary(readTravelProject());hero(panel,'What have you collected?',`${summary.length} imported datasets · ${summary.reduce((n,t)=>n+t.rows,0)} rows`,'▤');if(!summary.length){panel.append(make('p','tool-help','Import a dataset to see its size, fields and completeness here.'),button('Import data',()=>go(SOCIAL_IMPORT),'tool-primary'));return;}grid(panel,summary.map(t=>()=>{const item=tile(t.name,`${t.rows} rows · ${t.columns} fields`,'▤',()=>inspect(t.id));const meter=make('meter');meter.min=0;meter.max=t.cells||1;meter.value=t.filled;meter.setAttribute('aria-label',`${t.filled} of ${t.cells} cells populated`);item.append(meter);return item;}),6);panel.append(button('Allocate in the matrix',()=>{location.href='matrix.html?from='+page.id;},'tool-primary'));}
 function inspect(id){const t=readTravelProject().tables.find(t=>t.id===id);header(panel,t.name,home);hero(panel,'Field overview','Counts describe the imported data. They do not infer personality or relationships.','▤');grid(panel,t.columns.map((name,i)=>()=>{const values=t.rows.map(r=>r.values[i]).filter(v=>v.trim()),unique=new Set(values);return tile(name,`${values.length} filled · ${unique.size} distinct values`,'▤',()=>{header(panel,name,()=>inspect(id));const view=make('textarea','tool-read');view.readOnly=true;view.value=[...unique].join('\n');panel.append(view);});}),6);panel.append(button('Export table',()=>download(t.name+'.json',t)));}
 home();return {resize(){},dispose(){}};
}
